The general text for the manual is located in the directory pointed to by the parameter _MANUAL_SRC_.
This directory must have the following layout and contents:

[source%nowrap]
----
MANUAL_SRC
    ├─── application                <1>
    │    ├─── authors.adoc          <2>
    │    ├─── bugs.adoc             <3>
    │    ├─── copying.adoc          <4>
    │    ├─── description.adoc      <5>
    │    ├─── resources.adoc        <6>
    │    └─── security.adoc         <7>
    ├─── elements                   <8>
    │    ├─── commands.adoc         <9>
    │    ├─── dependencies.adoc     <10>
    │    ├─── exit-options.adoc     <11>
    │    ├─── exit-status.adoc      <12>
    │    ├─── options.adoc          <13>
    │    ├─── parameters.adoc       <14>
    │    ├─── run-options.adoc      <15>
    │    ├─── scenarios.adoc        <16>
    │    └─── tasks.adoc            <17>
    └─── tags                       <18>
         ├─── authors.txt           <19>
         └─── name.txt              <20>
----
<1> Directory with general application text, the `.adoc` source must be present, the `.txt` files can be generated using the target _src_.
    For multi-paragraph text, use an empty line to separate paragraphs.
    To add a list, add an empty line and then each list element in a single line starting with an asterisk `*`.
    Finish the list with an empty line.
    Nested lists are not supported.
<2> List of authors.
<3> Statements on bugs, known problems, etc.
<4> Statements on copyright, licenses, etc.
<5> A description of the application.
<6> Links to resources, for instance a source repository or issue management or a web site.
<7> Statements on security concerns when using the application.
<8> Directory with text for the framework elements, the `.adoc` source must be present, the `.txt` files can be generated using the target _src_.
    For the ADOC source, the same rules as for the _application_ directory apply.
<9> Introduction to shell commands.
<10> Introduction and text for dependencies.
<11> Text for _exit_ command line options.
<12> Text for exit status codes and error messages.
<13> Introduction and text for command line options.
<14> Introduction and text for parameters.
<15> Text for _runtime_ command line options.
<16> Introduction and text for scenarios.
<17> Introduction and text for tasks.
<18> Directory with tags, these files are used as plain text files.
<19> A list of authors, used in the ADOC file header.
<20> A tag line for the application, used in the _name_ and _synopsis_ sections.
