//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== Build Tasks
This category of tasks either _builds_ artifacts or _compiles_ source files to create artifacts.
Those tasks should be available in the application mode _build_, but no _use_.
They might be available in the application mode _dev_ if required.
The exception to this general rule is the task `build-manual`, since it can be used to build an application-mode-specific manual and might thus be required in all application modes.

By conventions, all _build_ and _compile_ tasks should provide an argument `-c` or `--clean`.
This argument should clean (remove) all built or compiled artifacts (and directories if applicable).
