
:release-version: 0.0.1
= SKB Framework
v{release-version}
:page-layout: base
:toc: preamble

a flexible, metadata driven application framework.


== Overview

The framework is written in `bash` and runs on most UNIX platforms that have `bash` version 4 installed.
We have tested it on

* Ubuntu 14/16/18
* Debian 3
* Raspian (on PI model B and B+)
* Cygwin on Windows 7 and 10
* Windows 10 WSL with Ubuntu 18 installed
* Mac OS X


----
sudo add-apt-repository ppa:vdmeer/skb
sudo apt-get update 
sudo apt-get install skb-framework
sudo -u skbused skb-framework 

(the last line only to make sure it runs as the created user, can run as any user) 
----


=== Requirements

==== to use
The program has a few mandatory external dependencies, listed below.
All of them are part of a standard Linux system with GNU tools.
On some system, a manual installation can be required.
For instance, Raspian does not install `bc` by default.
Mac OS might require special attention to install GNU tools, e.g. with `brew`.

* `bash` version 4, since we are using associative arrays (hash maps) for internal configuration
* GNU `getopt`, all CLI parsing is done using getopt from GNU
* `bc`, for some calculations, mostly runtime
* `mktemp`, for creating temporary files and directories

==== to build distributions

To build distribution packages (DEB, RPM, tarball):

* `gradle` version 4, the build uses gradle, a gradlew is provided

==== to build all artifacts

Generating nicely formated text paragraphs and list requires:

* `gradle` version 4, the build is done with gradle (gradlew is provided)

Not mandatory, but required to build all documentation artifacts are:

* `asciidoctor`, to create HTML and man page from ADOC sources
* `asciidoctor-pdf`, to create PDF from ADOC sources

To generate the site for the program requires:

* `Java` JDK 8, since we are using Maven
* Apache `Maven`, since the site is written as a Maven site



