//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== cloc-installation

This tasks counts the lines of code of an installation.
It is available in all application modes.

The task forces files that `cloc` identifies as _sh_ files to be treated as _bash_ files, using the `cloc` option `--force-lang="Bourne Again Shell",sh`.
This ensures that the installation's include and application files (without the `.sh` extension) are counted as _bash_ files.

More details on `cloc` can be found at the Github source repository on link:https://github.com/AlDanial/cloc[Github].



=== Options

The task does not have any special options.

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/cloc-installation.adoc[tags=options]
----



=== Examples

Simply running the task will count the lines of code of an installation.
The following is the output of running this task on the SKB-Framework version {release-version}.

[source%nowrap,subs="attributes"]
----
include::{skb-site-target-dir}/adoc-text/cloci.txt[]
----

The count shows the two ANT files (build file and macro file) as ANT and XML language files.
All ADOC files are shown as AsciiDoc language files
The HTML file is the framework's HTML manual.
The top line shows the lines of code for all _bash_ scripts in the installation, including all tasks and `.id` files.



=== Requirements

The task requires the tool `cloc` being installed.
The dependency is called by the same name: _cloc_.
If `cloc` is not installed, the task will print an error.
