//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== describe-*

There are nine tasks that start with _describe-_.
Each of these tasks provides a description of one or more framework and application features, namely:

* _describe-application_ - describes one or more application aspects (from the manual)
* _describe-command_ - describes one or more shell commands
* _describe-dependency_ - describes one or more dependencies
* _describe-element_ - describes one or more element types of an application
* _describe-errorcode_ - describes one or more error codes
* _describe-option_ - describes one or more CLI options
* _describe-parameter_ - describes one or more parameters
* _describe-scenario_ - describes one or more scenarios
* _describe-task_ - describes one or more tasks

All of these tasks have the same default behavior, provide the same main options, and can be used with (then task specific) filters.
The default behavior, when executed without any arguments, is to provide a list of descriptions.
For example, when _describe-task_ is called it provides list of task descriptions, one per declared task.
The description will be empty if no items where found, e.g. in _describe-scenario_ when no scenarios have been loaded.

The standard options are shown below.
_print-mode_ can be set to any mode that is supported by the API, namely:

* _adoc_ - print in Asciidoc format
* _ansi_ - print with ANSI formatting for colors and effects
* _text_ - print as plain text, no special formatting will be used
* _text-anon_ - print as text with some annotations, similar to _adoc_

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/describe-parameter.adoc[tags=standard-options]
----

All describe tasks provide filters to include or exclude entries.
The tasks have a standard filter for describing all items, shown below.
All other filters are task specific.
If filters are used, only items that satisfy the filter will be described.
Any number of filters can be used in any combination.

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/describe-parameter.adoc[tags=standard-filters]
----

For all task-specific filters: if not stated otherwise, these filters exclude any entry that does not fit the filter.
For instance, if a filter for _origin_ with setting _framework_ is activated, entries with origins other than _framework_ will not be described.

All filters are applied in combination.
This means that when two or more filters are active, only elements matching all filters will be described.
For instance, if filters for a specific _origin_ and a specific _status_ are activated, then all elements matching the origin _and_ the status will be described (and no element not matching both filters).

Tasks that describe elements (e.g. task, parameter, dependency) also provide a filter to only describe a single element by name (identifier).



=== describe-application
Describe application aspects from the manual.
The provided filters focus on the different aspects.
If filters are used, only aspects specified will be shown.
If no filters are used, all aspects are shown.

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/describe-application.adoc[tags=task-filters]
----

The text is taken from the manual.
This _MANUAL_SRC_ must point to valid manual sources.



=== describe-command
Describes one or more commands.
The _id_ filter can be used to show only a specific command.
For the _id_, the long or the short form of the command can be used.

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/describe-command.adoc[tags=task-filters]
----



=== describe-dependency
Describes one or more dependencies.
Provided filters are:

* _id_ - identifies a specific dependency and only this one will be described
* _install_ - only dependencies that are only required by tasks that run in `install` application mode flavor
* _origin_ - filter by declaration origin
    ** framework (as: `F`, `f`, `fw`, or `framework`), or
    ** application (as: `A`, `a`, `app`, or `application`)
* _requested_ - show dependencies that have been requested by a loaded task
* _status_ - filter by dependency status
    ** success (as: `S`, `s`, or `success`),
    ** warnings (as: `W`, `w`, or `warning`),
    ** errors (as: `E`, `e`, or `error`), or
    ** not attempted (as: `N`, `n`, or `not-attempted`)
* _tested_ - filter dependencies that have been tested, ignoring untested dependencies

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/describe-dependency.adoc[tags=task-filters]
----

This task can also be used to show debug information, rather than descriptions.
Using the debug option will print all information about one or more dependencies (depending on the used filters).

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/describe-dependency.adoc[tags=task-options]
----



=== describe-element
Describes framework and application element types, e.g. task, parameter, and description.
The text is the same as used in the manual as introduction to the elements.
The provided filters focus on the different element types.
If filters are used, only types specified will be shown.
If no filters are used, all types are shown.

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/describe-element.adoc[tags=task-filters]
----

The text is taken from the manual.
This _MANUAL_SRC_ must point to valid manual sources.



=== describe-errorcode
Describes one or more error codes.
The _id_ filter can be used to show only a specific error code.

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/describe-errorcode.adoc[tags=task-filters]
----



=== describe-option
Describes one or more command line options.
The _id_ filter can be used to show only a specific option.
For the _id_, the long or the short form of the option can be used.
The other filters focus on the option type, being either _exit_ options or _runtime_ options.

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/describe-option.adoc[tags=task-filters]
----



=== describe-parameter
Describes one or more parameters.
The following filters are provided:

* _default_ - describe parameters with a set default value
* _id_ - only describe a specific parameter, the identifier can be given in lower-case or upper-case or mixed spelling
* _install_ - only parameters that are only required by tasks that run in `install` application mode flavor
* _origin_ - filter by declaration origin
    ** framework (as: `F`, `f`, `fw`, or `framework`), or
    ** application (as: `A`, `a`, `app`, or `application`)
* _requested_ - show parameters that have been requested by a loaded task
* _status_ - filter for parameter setting status
    ** not set (as `N`, `n`, or `notset`)
    ** set from command line option (as: `O`, `o`, `option`)
    ** set from environment (as `E`, `e`, `env`, `environment`)
    ** set from configuration file (as `F`, `f`, `file`)
    ** set from default value (as `D`, `d`, `default`)

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/describe-parameter.adoc[tags=task-filters]
----

This task can also be used to show debug information, rather than descriptions.
Using the debug option will print all information about one or more parameters (depending on the used filters).

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/describe-parameter.adoc[tags=task-options]
----



=== describe-scenario
Describes one or more scenarios.
Provided filters are:

* _id_ - only describe a specific scenario, the identifier can be the long name or the short name of the scenario
* _install_ - only scenarios that are defined for the `install` application mode flavor
* _loaded_ - show only scenarios currently loaded
* _mode_ - show only scenarios for a specific application mode
    ** for mode _all_ use    `A`, `a`, `All`,   `all`
    ** for mode _dev_ use    `D`, `d`, `Dev`,   `dev`
    ** for mode _build_ use  `B`, `b`, `Build`, `build`
    ** for mode _use_ use    `U`, `u`, `Use`,   `use`
* _origin_ - * _origin_ - filter by declaration origin
    ** framework (as: `F`, `f`, `fw`, or `framework`), or
    ** application (as: `A`, `a`, `app`, or `application`)
* _status_ - filter by scenario status
    ** success (as: `S`, `s`, or `success`),
    ** warnings (as: `W`, `w`, or `warning`),
    ** errors (as: `E`, `e`, or `error`), or
    ** not attempted (as: `N`, `n`, or `not-attempted`)
* _unloaded_ - filter for scenarios that have been unloaded

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/describe-scenario.adoc[tags=task-filters]
----

This task can also be used to show debug information, rather than descriptions.
Using the debug option will print all information about one or more dependencies (depending on the used filters).

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/describe-scenario.adoc[tags=task-options]
----



=== describe-task
Describes one or more tasks.
Provided filters are:

* _id_ - only describe a specific task, the identifier can be the long name or the short name of the task
* _install_ - include tasks that are defined for the `install` application mode flavor
* _loaded_ - show only tasks currently loaded
* _mode_ - show only tasks for a specific application mode
    ** for mode _all_ use    `A`, `a`, `All`,   `all`
    ** for mode _dev_ use    `D`, `d`, `Dev`,   `dev`
    ** for mode _build_ use  `B`, `b`, `Build`, `build`
    ** for mode _use_ use    `U`, `u`, `Use`,   `use`
* _origin_ - * _origin_ - filter by declaration origin
    ** framework (as: `F`, `f`, `fw`, or `framework`), or
    ** application (as: `A`, `a`, `app`, or `application`)
* _status_ - filter by task status
    ** success (as: `S`, `s`, or `success`),
    ** warnings (as: `W`, `w`, or `warning`),
    ** errors (as: `E`, `e`, or `error`), or
    ** not attempted (as: `N`, `n`, or `not-attempted`)
* _unloaded_ - filter for tasks that have been unloaded

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/describe-task.adoc[tags=task-filters]
----

This task can also be used to show debug information, rather than descriptions.
Using the debug option will print all information about one or more tasks (depending on the used filters).

[source%nowrap,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/describe-task.adoc[tags=task-options]
----
