//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== download-fw-tool

This tasks uses download and remote copt tools to download the SKB Framework Tool.
The framework tool is an executable Java JAR file, including all dependencies.
It is published on Bintray using the same version as the SKB Framework.
The URL for download (without the filename) is: https://dl.bintray.com/vdmeer/generic/ .

The framework tool provides mechanisms to convert ADOC text into formatted plain text.
It is used for instance by the task `build-manual` to create formatted text versions of the manual.

The task uses the setting of the parameter `SKB_FRAMEWORK_TOOL` to determine which JAR file it should download.
The output directory will be created if it does not exist.
If the JAR file already exists, no download will be started (use the force option to force a download).



=== Options

The option _simulate_ can be used to simulate all task actions.
In this mode, the task will only print what it would do.
The option _force_ can be used to force a download even if the JAR file already exists.
_simulate_ will overwrite _force_.

ifdef::backend-pdf[]
[source%nowrap,bash,indent=0,subs="attributes"]
----
include::{skb-site-target-dir}/adoc-screens/task-help/download-fw-tool--help--pdf.adoc[tags=options]
----
endif::[]
ifdef::backend-html5[]
[source%nowrap,bash,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-screens/task-help/download-fw-tool--help--adoc.adoc[tags=options]
----
endif::[]

The options for tools allow to select a download tool.
The default is _curl_.
The other option is to use _wget_.
All tools are marked as optional dependencies for the task.
The selected tool must be a successfully loaded dependency, otherwise an error message will be printed and no download is performed.

ifdef::backend-pdf[]
[source%nowrap,bash,indent=0,subs="attributes"]
----
include::{skb-site-target-dir}/adoc-screens/task-help/download-fw-tool--help--pdf.adoc[tags=tools]
----
endif::[]
ifdef::backend-html5[]
[source%nowrap,bash,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-screens/task-help/download-fw-tool--help--adoc.adoc[tags=tools]
----
endif::[]
