//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== list-*

There are eight tasks that start with _list-_.
Each of these tasks provides a list of framework and application features, namely:

* _list-commands_ - lists shell commands
* _list-configuration_ - list current configuration keys and values
* _list-dependencies_ - lists dependencies
* _list-exitstatus_ - lists exit status, error codes
* _list-options_ - lists CLI options
* _list-parameters_ - lists parameters
* _list-scenarios_ - lists scenarios
* _list-tasks_ - lists tasks

All of these tasks have the same default behavior, provide the same main options, and can be used with (then task specific) filters.
The default behavior, when executed without any arguments, is to provide a simple list.
For example, when _list-tasks_ is called it provides a simple list of tasks.
For each item in the list, the tasks show the identifier (or key), if available a short identifier, and a description (e.g. for tasks) or values (e.g. for _list-configuration_).
The list will be empty if no items where found, e.g. in _list-scenarios_ when no scenarios have been loaded.

The standard options are shown below.
Each of the list tasks provides a _table_ view, which provides more detailed information for their items.
The list tasks can also use a print mode different than the currently configured.
_print-mode_ can be set to any mode that is supported by the API, namely:

* _adoc_ - print in AscciDoc format
* _ansi_ - print with ANSI formatting for colors and effects
* _text_ - print as plain text, no special formatting will be used
* _text-anon_ - print as text with some annotations, similar to _adoc_

[source%nowrap,bash,indent=0]
----
   -h | --help              print help screen and exit
   -P | --print-mode MODE   print mode: ansi, text, adoc
   -T | --table             help screen format
----

All list tasks with filters provide a standard filter for listing all items, shown below.
All other filters are task specific.
If filters are used, only items that satisfy the filter will be listed.
Any number of filters can be used in any combination.

[source%nowrap,bash,indent=0]
----
   filters
   -A | --all               all settings, disables all other filters
----


=== list-commands
List the shell commands.
This task does not provide any further options or filters.

=== list-configuration
Lists configurations keys and values.
For print mode _ansi_, some of the values are color-coded or printed in bold or italic, for example:

* Values for application mode: _use_ printed in green, _build_ printed in blue, _dev_ printed in yellow, _all_ printed in dark red
* Values for levels: _error_ printed in red, _warn_ printed in yellow, _info_ printed in green, _debug_ and _trace_ printed in blue
* Value for flavor: printed in bold
* Values for quiet settings: _off_ printed in green, _on_ printed in red

In table mode, a color coded status indicates from where a setting was taken.

The task offers a number of filters.
They all relate to the original source from which a configuration value was set: command line, environment, configuration file, default value, or internally.

[source%nowrap,bash,indent=0]
----
   filters
   -c | --cli               only settings from CLI options
   -d | --default           only settings from default value
   -e | --env               only settings from environment
   -f | --file              only settings from configuration file
   -i | --internal          only internal settings
----

This task can take the list of items from the framework or application cache.
If _CACHE_DIR_ is set to a directory that contains cached command information (map), this information is used.



=== list-dependencies
Lists dependencies with name and description.
Table mode shows two more aspects of dependencies:
    the origin of its declaration (framework or application) and
    the load status (color coded).

Provided filters:

* _install_ - only dependencies that are only required by tasks that run in `install` application mode flavor
* _origin_ - filter by declaration origin
    ** framework (as: `F`, `f`, `fw`, or `framework`), or
    ** application (as: `A`, `a`, `app`, or `application`)
* _requested_ - show dependencies that have been requested by a loaded task
* _status_ - filter by dependency status
    ** success (as: `S`, `s`, or `success`),
    ** warnings (as: `W`, `w`, or `warning`),
    ** errors (as: `E`, `e`, or `error`), or
    ** not attempted (as: `N`, `n`, or `not-attempted`)
* _tested_ - filter dependencies that have been tested, ignoring untested dependencies

[source%nowrap,bash,indent=0]
----
   filters
   -I | --install           only dependencies required only by install tasks
   -o | --origin ORIGIN     only dependencies from origin: f(w), a(pp)
   -r | --requested         only requested dependencies
   -s | --status STATUS     only dependencies with status: (s)uccess, (w)arning, (e)rror, (n)ot attempted
   -t | --tested            only tested dependencies
----

This task can take the list of items from the framework or application cache.
If _CACHE_DIR_ is set to a directory that contains cached dependency information (map), this information is used.



=== list-exitstatus
Lists exit status codes with their number and description.
Table mode shows two more aspects:
    the origin (of an error: all, application, framework, loader, shell, tasks) and
    an indicator of the problem (internal for a bug, external for a configuration problem).
Provided filters focus on the _origin_ of the problem.

[source%nowrap,bash,indent=0]
----
   filters
        --app               only application status
   -f | --fw                only framework status
   -l | --loader            only loader status
   -s | --shell             only shell status
   -t | --task              only task status
----

This task can take the list of items from the framework or application cache.
If _CACHE_DIR_ is set to a directory that contains cached exit status information (map), this information is used.



=== list-options
Lists command line options with name, short name, if required a parameter, and a description.
Table mode also shows the type of option, being either an _exit_ option or a _runtime_ option.
Provided filters focus on the option type.

[source%nowrap,bash,indent=0]
----
   filters
   -e | --exit              only exit options
   -r | --run               only runtime options
----

This task can take the list of items from the framework or application cache.
If _CACHE_DIR_ is set to a directory that contains cached option information (map), this information is used.



=== list-parameters
Lists parameters with their name and description.
Table mode shows three more aspects of parameters:
        the origin of its declaration (framework or application),
        an indicator for a defined default value (red cross for not defined, green ok for defined), and
        a color coded load status.

The task also provides a second table.
This table shows the parameter names with their declared default value.

[source%nowrap,bash,indent=0]
----
   options
   -D | --def-table         print default value table
----

Provided filters are:

* _default_ - show parameters with a set default value
* _install_ - only parameters that are only required by tasks that run in `install` application mode flavor
* _origin_ - filter by declaration origin
    ** framework (as: `F`, `f`, `fw`, or `framework`), or
    ** application (as: `A`, `a`, `app`, or `application`)
* _requested_ - show parameters that have been requested by a loaded task
* _status_ - filter for parameter setting status
    ** not set (as `N`, `n`, or `notset`)
    ** set from command line option (as: `O`, `o`, `option`)
    ** set from environment (as `E`, `e`, `env`, `environment`)
    ** set from configuration file (as `F`, `f`, `file`)
    ** set from default value (as `D`, `d`, `default`)

[source%nowrap,bash,indent=0]
----
   filters
   -d | --default           only parameters with a defined default value
   -I | --install           only parameters required only by install tasks
   -o | --origin ORIGIN     only parameters from origin: f(w), a(pp)
   -r | --requested         only requested dependencies
   -s | --status STATUS     only parameter for status: o, f, e, d
----

This task can take the list of items from the framework or application cache.
If _CACHE_DIR_ is set to a directory that contains cached parameter information (map), this information is used.



=== list-scenarios
Lists scenarios with their name, short name, and a description.
Table mode shows a few more aspects of scenarios:

* the origin of its declaration (framework or application),
* the application mode flavor, being either `S` for `standard` or `std` or `I` for `install`,
* if the scenario is declared for application _dev_,
* if the scenario is declared for application _build_,
* if the scenario is declared for application _use_, and
* a color coded load status.

Provided filters are:

* _install_ - only scenarios that are defined for the `install` application mode flavor
* _loaded_ - show only scenarios currently loaded
* _mode_ - show only scenarios for a specific application mode
    ** for mode _all_ use    `A`, `a`, `All`,   `all`
    ** for mode _dev_ use    `D`, `d`, `Dev`,   `dev`
    ** for mode _build_ use  `B`, `b`, `Build`, `build`
    ** for mode _use_ use    `U`, `u`, `Use`,   `use`
* filters to exclude scenarios by name:
    ** _no-a_ for all these _no_ filters
    ** _no-b_ to exclude scenarios that start with `build-`
    ** _no-d_ to exclude scenarios that start with `describe-`
    ** _no-dl_ to exclude scenarios that start with `describe-` or `list-`
    ** _no-l_ to exclude scenarios that start with `list-`
    ** _no-s_ to exclude scenarios that start with `start-`
* _origin_ - * _origin_ - filter by declaration origin
    ** framework (as: `F`, `f`, `fw`, or `framework`), or
    ** application (as: `A`, `a`, `app`, or `application`)
* _odl_ - filter for scenarios that start with `describe-` or `list-`
* _status_ - filter by scenario status
    ** success (as: `S`, `s`, or `success`),
    ** warnings (as: `W`, `w`, or `warning`),
    ** errors (as: `E`, `e`, or `error`), or
    ** not attempted (as: `N`, `n`, or `not-attempted`)
* _unloaded_ - filter for scenarios that have been unloaded

[source%nowrap,bash,indent=0]
----
   filters
   -I | --install           only scenarios for application mode flavor 'install'
   -l | --loaded            only loaded scenarios
   -m | --mode MODE         only scenarios for application mode: dev, build, use
        --no-a              activate all '--no-' filters
        --no-b              exclude scenarios starting with 'build-'
        --no-d              exclude scenarios starting with 'describe-'
        --no-dl             exclude scenarios starting with 'describe-' or 'list-'
        --no-l              exclude scenarios starting with 'list-'
        --no-s              exclude scenarios starting with 'start-'
   -o | --origin ORIGIN     only scenarios from origin: f(w), a(pp)
        --odl               show only scenarios starting with 'describe-' or 'list-'
   -s | --status STATUS     only scenarios with status: (s)uccess, (w)arning, (e)rror, (n)ot attempted
   -u | --unloaded          only unloaded scenarios
----

This task can take the list of items from the framework or application cache.
If _CACHE_DIR_ is set to a directory that contains cached scenario information (map), this information is used.



=== list-tasks
Lists tasks with their name, short name, and a description.
Table mode shows a few more aspects of tasks:

* the origin of its declaration (framework or application),
* the application mode flavor, being either `S` for `standard` or `std` or `I` for `install`,
* if the task is declared for application _dev_,
* if the task is declared for application _build_,
* if the task is declared for application _use_, and
* a color coded load status.

Provided filters are:

* _install_ - only tasks that are defined for the `install` application mode flavor
* _loaded_ - show only tasks currently loaded
* _mode_ - show only tasks for a specific application mode
    ** for mode _all_ use    `A`, `a`, `All`,   `all`
    ** for mode _dev_ use    `D`, `d`, `Dev`,   `dev`
    ** for mode _build_ use  `B`, `b`, `Build`, `build`
    ** for mode _use_ use    `U`, `u`, `Use`,   `use`
* filters to exclude tasks by name:
    ** _no-a_ for all these _no_ filters
    ** _no-b_ to exclude tasks that start with `build-`
    ** _no-d_ to exclude tasks that start with `describe-`
    ** _no-dl_ to exclude tasks that start with `describe-` or `list-`
    ** _no-l_ to exclude tasks that start with `list-`
    ** _no-s_ to exclude tasks that start with `start-`
* _origin_ - * _origin_ - filter by declaration origin
    ** framework (as: `F`, `f`, `fw`, or `framework`), or
    ** application (as: `A`, `a`, `app`, or `application`)
* _odl_ - filter for tasks that start with `describe-` or `list-`
* _status_ - filter by task status
    ** success (as: `S`, `s`, or `success`),
    ** warnings (as: `W`, `w`, or `warning`),
    ** errors (as: `E`, `e`, or `error`), or
    ** not attempted (as: `N`, `n`, or `not-attempted`)
* _unloaded_ - filter for tasks that have been unloaded

[source%nowrap,bash,indent=0]
----
   filters
   -I | --install           only tasks for application mode flavor 'install'
   -l | --loaded            only loaded tasks
   -m | --mode MODE         only tasks for application mode: dev, build, use
        --no-a              activate all '--no-' filters
        --no-b              exclude tasks starting with 'build-'
        --no-d              exclude tasks starting with 'describe-'
        --no-dl             exclude tasks starting with 'describe-' or 'list-'
        --no-l              exclude tasks starting with 'list-'
        --no-s              exclude tasks starting with 'start-'
   -o | --origin ORIGIN     only tasks from origin: f(w), a(pp)
        --odl               show only tasks starting with 'describe-' or 'list-'
   -s | --status STATUS     only tasks with status: (s)uccess, (w)arning, (e)rror, (n)ot attempted
   -u | --unloaded          only unloaded tasks
----

This task can take the list of items from the framework or application cache.
If _CACHE_DIR_ is set to a directory that contains cached task information (map), this information is used.

