//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== repeat-task
This task will repeat a task _n_ times and wait for _s_ seconds between repetitions.
The values for _times_ and _wait_ must be positive integers.
The default values are repeat once (times = 1) and wait for 1 second (wait = 1).

ifdef::backend-pdf[]
[source%nowrap,bash,indent=0,subs="attributes"]
----
include::{skb-site-target-dir}/adoc-task-help/repeat-task--help--pdf.adoc[tags=options]
----
endif::[]
ifdef::backend-html5[]
[source%nowrap,bash,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/repeat-task--help--adoc.adoc[tags=options]
----
endif::[]

The task and task parameters should be provided after `--` in the command line.
This task assumes that the first word after `--` is the task name (or identifier, either the long or the short form) and all other characters are arguments.
The task name will be used to execute the task, the arguments then will not be processed but simply handed over to the executed task.


=== Examples

The example below will execute the task `list-tasks` with the arguments `-T --no-a` three times and wait for two seconds between repetitions.

[source%nowrap,bash,indent=0]
----
repeat-task --times 3 --wait 2 -- lt -T --no-a
----


The example below will do the exact same.
It simply uses the long name of the task and the long form of its arguments

[source%nowrap,bash,indent=0]
----
repeat-task --times 3 --wait 2 -- list-tasks --table --no-a
----

