//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== start-xterm
This task starts an X terminal, or short XTerm (or xterm), with a set title and command to run in it.
The title can be set with _title_.
For blanks in the title use quotes, for instance `--title "My XTERM"`.

[source%nowrap,bash,indent=0]
----
   -h | --help           print help screen and exit
   -t | --title TITLE    title for the XTerm, default: command name
----

The command to run in the started XTerm should be provided to the task after `--`.
The task assumes that the first word there is the command name (which then is used as the default title).
All text after `--` will be taken as command.

Note: this task does not take any effort to _hold_ the XTerm, i.e. to keep it open after the command finished.
Use the _hold_ option of your preferred XTerm in _XTERM_ to realize this feature.



=== Examples

Start an XTerm, use the default title, and run `ls | more` as command.
[example]
====
start-xterm -- ls | more
====



=== Requirements
The actual command for starting an XTerm must be provided in _XTERM_.
If this parameter is not set, the task will print an error and exit.
Examples for setting _XTERM_ are:

* standard executable: `xterm -T %TITLE% -e %COMMAND%`
* MinTTY on Cygwin: `mintty -t %TITLE% %COMMAND%`
* XFCE 4 Terminal: `xfce4-terminal --disable-server --title='%TITLE%' -x %COMMAND%`

More information on the parameter _XTERM_ can be found in the framework manual.
