//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== start-pdf-viewer
This task starts a PDF viewer with a file to show in it.
The file can be set with _file_.

ifdef::backend-pdf[]
[source%nowrap,bash,indent=0,subs="attributes"]
----
include::{skb-site-target-dir}/adoc-task-help/start-pdf-viewer--help--pdf.adoc[tags=options]
----
endif::[]
ifdef::backend-html5[]
[source%nowrap,bash,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-task-help/start-pdf-viewer--help--adoc.adoc[tags=options]
----
endif::[]

The task will test if the file is readable, and throw an error if not.
It will also use a system specific path if required (for instance on Cygwin).


=== Requirements
The actual command for starting a PDF viewer must be provided in _PDF_VIEWER_.
If this parameter is not set, the task will print an error and exit.
Examples for setting _PDF_VIEWER_ are:

* acrobat: `acrobat %FILE%`
* evince: `evince %FILE%`

More information on the parameter _PDF_VIEWER_ can be found in the framework manual.
