//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//


== start-pdf-viewer
This task starts a PDF viewer with a file to show in it.
The file can be set with _file_.

[source%nowrap,bash,indent=0]
----
   -h | --help        print help screen and exit
   -f | --file FILE   PDF file to open in reader
----

The task will test if the file is readable, and throw an error if not.
It will also use a system specific path if required (for instance on Cygwin).


=== Requirements
The actual command for starting a PDF viewer must be provided in _PDF_VIEWER_.
If this parameter is not set, the task will print an error and exit.
Examples for setting _PDF_VIEWER_ are:

* acrobat: `acrobat %FILE%`
* evince: `evince %FILE%`

More information on the parameter _PDF_VIEWER_ can be found in the framework manual.
