//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== statistics
This task prints statistics about the all elements.
The default, without using filters, is to print a few overview tables.
The print mode can be changed using _print-mode_.

ifdef::backend-pdf[]
[source%nowrap,bash,indent=0,subs="attributes"]
----
include::{skb-site-target-dir}/adoc-screens/task-help/statistics--help--pdf.adoc[tags=options]
----
endif::[]
ifdef::backend-html5[]
[source%nowrap,bash,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-screens/task-help/statistics--help--adoc.adoc[tags=options]
----
endif::[]

=== Filters
Using filters will provide more detailed information.
Any number of filters can be used in any sequence, the tasks will print the output always in the same order:

* Overview table (default, or if filter is set)
* Commands (if filter is set)
* Dependencies (if filter is set)
* Error Codes (if filter is set)
* Options (if filter is set)
* Parameters (if filter is set)
* Tasks (if filter is set)
* Scenarios (if filter is set)

ifdef::backend-pdf[]
[source%nowrap,bash,indent=0,subs="attributes"]
----
include::{skb-site-target-dir}/adoc-screens/task-help/statistics--help--pdf.adoc[tags=filters]
----
endif::[]
ifdef::backend-html5[]
[source%nowrap,bash,indent=0,subs="attributes,quotes"]
----
include::{skb-site-target-dir}/adoc-screens/task-help/statistics--help--adoc.adoc[tags=filters]
----
endif::[]



=== Examples

The following example requests statistics for the target overview _--ov_ and tasks _--task_.

[source%nowrap,bash,indent=0]
----
stats --ov --task
----

The actual output depends of course on the declared and processed tasks.
the following screen shows the statistics for the SKB-Framework version {release-version}, started in _all_ mode and _install_ flavor and with all settings required to build the distribution.

[source%nowrap,subs="attributes"]
----
include::{skb-site-target-dir}/adoc-screens/text/stats.txt[]
----
