//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== Console

One important aspect of an interactive shell is to write messages and text to the console.
The functions here are provided to standardize this part of the user interface.
They are written similar to what one will find in logging frameworks, such as the Java framework `log4j`.
Messages can be of general nature, or specific to situations for
    _fatal errors, standard _errors_, _warnings_, _information_, _debug_ information, or program execution _trace_(s)
For _warnings_ and _errors_, the console functions will also increase the associated counters.

One special case is _warn-strict_.
If the application is running in a normal mode (`strict` not activated), then strict warnings are treated as warnings.
However, if the application is running in `strict` mode, then strict warnings are treated as errors.


=== ConsoleMessage
Prints a message to the console (standard error).
The function uses `CONFIG_MAP["RUNNING_IN"]` to determine which setting to use:
    `CONFIG_MAP["LOADER_QUIET"]` for the loader,
    `CONFIG_MAP["SHELL_QUIET"]` for the shell, or
    `CONFIG_MAP["TASK_QUIET"]` for tasks.
If the setting for quiet is _off_, it prints the message.
Otherwise it does not print the message.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return

| $1: the message
| none

|===


[example]
====
ConsoleMessage "message"
====



=== ConsoleIsMessage
Returns the message status.
The function uses `CONFIG_MAP["RUNNING_IN"]` to determine which setting to use:
    `CONFIG_MAP["LOADER_QUIET"]` for the loader,
    `CONFIG_MAP["SHELL_QUIET"]` for the shell, or
    `CONFIG_MAP["TASK_QUIET"]` for tasks.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return (print)

| none
| 1 for _on_, 0 for _off_

|===


[example]
====
if ConsoleIsMessage; then ...; else ...; fi
====



=== ConsoleIsPrompt
Returns shell-prompt status from `CONFIG_MAP["SHELL_SNP"]`.
The function uses `CONFIG_MAP["RUNNING_IN"]` to determine which setting to use:
    `CONFIG_MAP["LOADER_QUIET"]` for the loader,
    `CONFIG_MAP["SHELL_QUIET"]` for the shell, or
    `CONFIG_MAP["TASK_QUIET"]` for tasks.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return (print)

| none
| 1 for _on_, 0 for _off_

|===


[example]
====
if ConsoleIsPrompt; then ...; else ...; fi
====



=== ConsoleFatal
Prints an error message with _[Fatal]_ tag if the level for _fatal_ is set and increases the error counter.
The function uses `CONFIG_MAP["RUNNING_IN"]` to determine which setting to use:
    `CONFIG_MAP["LOADER_LEVEL"]`and `LOADER_ERRORS` counter for the loader,
    `CONFIG_MAP["SHELL_LEVEL"]` and `SHELL_ERRORS` counter for the shell, or
    `CONFIG_MAP["TASK_LEVEL"]` and `TASK_ERRORS` counter for tasks.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return (print)

| $1: message prefix, e.g. script name with colon

$2: the error message
| none

|===


[example]
====
ConsoleFatal "  ->" "fatal error message"
====



=== ConsoleError
Prints an error message with _[Error]_ tag if the level for _fatal_ is set and increases the error counter.
The function uses `CONFIG_MAP["RUNNING_IN"]` to determine which setting to use:
    `CONFIG_MAP["LOADER_LEVEL"]` and `LOADER_ERRORS` counter for the loader,
    `CONFIG_MAP["SHELL_LEVEL"]` and `SHELL_ERRORS` counter for the shell, or
    `CONFIG_MAP["TASK_LEVEL"]` and `TASK_ERRORS` counter for tasks.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return (print)

| $1: message prefix, e.g. script name with colon

$2: the error message
| none

|===


[example]
====
ConsoleError "  ->" "error message"
====



=== ConsoleResetErrors
Resets the error counter, i.e. sets it to _0_.
The function uses `CONFIG_MAP["RUNNING_IN"]` to determine which counter to reset:
    `LOADER_ERRORS` for the loader,
    `SHELL_ERRORS` for the shell, or
    `TASK_ERRORS` for tasks.

[example]
====
ConsoleResetErrors
====



=== ConsoleHasErrors
Returns _true_ if the counter has errors (i.e. is larger than _0_) or false if it does not have errors (i.e. is _0_).
The function uses `CONFIG_MAP["RUNNING_IN"]` to determine which counter to use:
    `LOADER_ERRORS` for the loader,
    `SHELL_ERRORS` for the shell, or
    `TASK_ERRORS` for tasks.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return

| none
| _true_ (0) if errors

_false_ (1) if no errors

|===

[example]
====
if ConsoleHasErrors; then ...; ...; fi

if ConsoleHasErrors; then ...; else ...; fi
====



=== ConsoleWarnStrict
Prints a strict warning message.
If the application is not in strict mode, those messages are considered warnings.
Here, the message will be printed with the tag _[Warn/Strict]_ and the warning counter will be increased.
If the application is in strict mode, those messages are considered errors.
Here, the message will be printed with the tag _[Error/Strict]_ and ere, the error counter will be increased.
In _ansi_ print mode, _Warn_ is yellow and _Error_ is red.
The function uses `CONFIG_MAP["RUNNING_IN"]` and `CONFIG_MAP["STRICT"]` to determine which counter to increase.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return

| $1: message prefix, script name with colon

$2: the warning/error message
| none

|===

[example]
====
ConsoleWarnStrict "  ->" "did not find file $FILE"
====



=== ConsoleWarn
Prints a warning message.
The message will be printed with the tag _[Warn]_ and the warning counter will be increased.
If the application is in strict mode, those messages are considered errors.
The function uses `CONFIG_MAP["RUNNING_IN"]` to determine which counter to increase:
    `LOADER_WARNINGS` for the loader,
    `SHELL_WARNINGS` for the shell, or
    `TASK_WARNINGS` for tasks.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return

| $1: message prefix, script name with colon

$2: the warning message
| none

|===

[example]
====
ConsoleWarn "  ->" "did not find file $FILE"
====



=== ConsoleResetWarnings
Resets the warning counter, i.e. sets it to _0_.
The function uses `CONFIG_MAP["RUNNING_IN"]` to determine which counter to reset:
    `LOADER_WARNINGS` for the loader,
    `SHELL_WARNINGS` for the shell, or
    `TASK_WARNINGS` for tasks.

[example]
====
ConsoleResetWarnings
====



=== ConsoleHasWarnings
Returns _true_ if the counter has warnings (i.e. is larger than _0_) or false if it does not have warnings (i.e. is _0_).
The function uses `CONFIG_MAP["RUNNING_IN"]` to determine which counter to use:
    `LOADER_WARNINGS` for the loader,
    `SHELL_WARNINGS` for the shell, or
    `TASK_WARNINGS` for tasks.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return

| none
| _true_ (0) if warnings

_false_ (1) if no warnings

|===

[example]
====
if ConsoleHasWarnings; then ...; ...; fi

if ConsoleHasWarnings; then ...; else ...; fi
====



=== ConsoleInfo
Prints an information message.
The message will be printed with the tag _[Info]_.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return

| $1: message prefix, script name with colon

$2: the message
| none

|===

[example]
====
ConsoleInfo "  ->" "I am doing something now"
====



=== ConsoleDebug
Prints a debug message.
The message will be printed with the prefix `    >` in bold.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return

| $1: the message
| none

|===

[example]
====
ConsoleDebug "I am doing something now"
====



=== ConsoleTrace
Prints a trace message.
The message will be printed with the prefix `    >` in italic.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return

| $1: the message
| none

|===

[example]
====
ConsoleTrace "I am doing something now"
====



=== ConsoleIsDebug
Returns the message status.
The function uses `CONFIG_MAP["RUNNING_IN"]` to determine which setting to use:
    `CONFIG_MAP["LOADER_LEVEL"]` for the loader,
    `CONFIG_MAP["SHELL_LEVEL"]` for the shell, or
    `CONFIG_MAP["TASK_LEVEL"]` for tasks.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return (print)

| none
| 1 for _on_, 0 for _off_

|===


[example]
====
if ConsoleIsDebug; then ...; else ...; fi
====



=== ConsoleIsTrace
Returns the message status.
The function uses `CONFIG_MAP["RUNNING_IN"]` to determine which setting to use:
    `CONFIG_MAP["LOADER_LEVEL"]` for the loader,
    `CONFIG_MAP["SHELL_LEVEL"]` for the shell, or
    `CONFIG_MAP["TASK_LEVEL"]` for tasks.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return (print)

| none
| 1 for _on_, 0 for _off_

|===


[example]
====
if ConsoleIsTrace; then ...; else ...; fi
====


