//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== Execute

=== ExecuteTask
Executes a task.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return

| $1: full command line for the task
| none

|===

The first word from the argument is taken as the task name.
This can be the task's short or long name.
The task must be loaded and available for execution.

This function will print extra information (header and footer, execution time calculations) for most tasks.
The exception here are all _standard_ tasks known to not need header and footers: _list-*_, _describe-*_, _setting_, _manual_, _statistics_, and _wait_.
Also: any task execution that includes the arguments `-h` or `--help` will not see header and footer printed.
For the task _wait_, an additional calculation of the actual wait time is displayed.


[example]
====
ExecuteTask "$SARG"

ExecuteTask "list-tasks -AT"
====



=== ExecuteScenario
Executes a scenario.

[frame=topbot, grid=rows, cols="d,d", options="header"]
|===

| Arguments
| Return

| $1: scenario ID, short or long
| none

|===

The scenario must be loaded and available for execution.


[example]
====
ExecuteScenario build-site
====
