//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== Function Index
Collection of functions for tasks.


=== Alphabetically

[frame=none, grid=none, cols="a,a,a,a"]
|===

|
ifeval::["{adoc-build-target}" == "pdf"]
<<_buildtaskhelpline>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_buildtaskhelpline>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:tasks.html#buildtaskhelpline[BuildTaskHelpLine]
endif::[]
| | |

|===

'''

[frame=none, grid=none, cols="a,a,a,a"]
|===

|
ifeval::["{adoc-build-target}" == "pdf"]
<<_consoledebug>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consoledebug>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consoledebug[ConsoleDebug]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_consolehaswarnings>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consolehaswarnings>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consolehaswarnings[ConsoleHasWarnings]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_consoleisprompt>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consoleisprompt>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consoleisprompt[ConsoleIsPrompt]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_consoleresetwarnings>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consoleresetwarnings>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consoleresetwarnings[ConsoleResetWarnings]
endif::[]
|
ifeval::["{adoc-build-target}" == "pdf"]
<<_consoleerror>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consoleerror>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consoleerror[ConsoleError]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_consoleinfo>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consoleinfo>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consoleinfo[ConsoleInfo]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_consoleistrace>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consoleistrace>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consoleistrace[ConsoleIsTrace]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_consoletrace>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consoletrace>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consoletrace[ConsoleTrace]
endif::[]
|
ifeval::["{adoc-build-target}" == "pdf"]
<<_consolefatal>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consolefatal>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consolefatal[ConsoleFatal]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_consoleisdebug>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consoleisdebug>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consoleisdebug[ConsoleIsDebug]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_consolemessage>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consolemessage>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consolemessage[ConsoleMessage]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_consolewarn>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consolewarn>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consolewarn[ConsoleWarn]
endif::[]
|
ifeval::["{adoc-build-target}" == "pdf"]
<<_consolehaserrors>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consolehaserrors>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consolehaserrors[ConsoleHasErrors]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_consoleismessage>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consoleismessage>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consoleismessage[ConsoleIsMessage]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_consolereseterrors>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consolereseterrors>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consolereseterrors[ConsoleResetErrors]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_consolewarnstrict>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_consolewarnstrict>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:console.html#consolewarnstrict[ConsoleWarnStrict]
endif::[]
|===

'''

[frame=none, grid=none, cols="a,a,a,a"]
|===

|
ifeval::["{adoc-build-target}" == "pdf"]
<<_executescenario>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_executescenario>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:execute.html#executescenario[ExecuteScenario]
endif::[]


|
ifeval::["{adoc-build-target}" == "pdf"]
<<_executetask>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_executetask>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:execute.html#executetask[ExecuteTask]
endif::[]
|
ifeval::["{adoc-build-target}" == "pdf"]
<<_exitontaskerrors>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_exitontaskerrors>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:misc.html#exitontaskerrors[ExitOnTaskErrors]
endif::[]
|
|===

'''

[frame=none, grid=none, cols="a,a,a,a"]
|===

|
ifeval::["{adoc-build-target}" == "pdf"]
<<_getcommandid>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_getcommandid>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:commands.html#getcommandid[GetCommandID]
endif::[]
|
ifeval::["{adoc-build-target}" == "pdf"]
<<_getscenarioid>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_getscenarioid>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:scenarios.html#getscenarioid[GetScenarioID]
endif::[]
|
ifeval::["{adoc-build-target}" == "pdf"]
<<_gettaskid>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_gettaskid>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:tasks.html#gettaskid[GetTaskID]
endif::[]
|
|===

'''

[frame=none, grid=none, cols="a,a,a,a"]
|===

|
ifeval::["{adoc-build-target}" == "pdf"]
<<_mvnsitefixadoc>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_mvnsitefixadoc>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:mvn-site.html#mvnsitefixadoc[MvnSiteFixAdoc]
endif::[]
|
ifeval::["{adoc-build-target}" == "pdf"]
<<_mvnsitefixadocarray>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_mvnsitefixadocarray>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:mvn-site.html#mvnsitefixadocarray[MvnSiteFixAdocArray]
endif::[]
| |
|===

'''

[frame=none, grid=none, cols="a,a,a,a"]
|===

|
ifeval::["{adoc-build-target}" == "pdf"]
<<_pathtosystempath>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_pathtosystempath>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:system.html#pathtosystempath[PathToSystemPath]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_printquiet>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_printquiet>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:print.html#printquiet[PrintQuiet]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_printtesteffects>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_printtesteffects>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:print-ansi.html#printtesteffects[PrintTestEffects]
endif::[]

|
ifeval::["{adoc-build-target}" == "pdf"]
<<_printappmode>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_printappmode>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:print.html#printappmode[PrintAppMode]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_printshellsnp>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_printshellsnp>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:print.html#printshellsnp[PrintShellSNP]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_printtestutf8>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_printtestutf8>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:print.html#printtestutf8[PrintTestUtf8]
endif::[]

|
ifeval::["{adoc-build-target}" == "pdf"]
<<_printappmodeflavor>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_printappmodeflavor>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:print.html#printappmodeflavor[PrintAppModeFlavor]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_printstrict>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_printstrict>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:print.html#printstrict[PrintStrict]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_promptsfmode>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_promptsfmode>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:prompt.html#promptsfmode[PromptSfMode]
endif::[]
|
ifeval::["{adoc-build-target}" == "pdf"]
<<_printconsolelevel>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_printconsolelevel>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:print.html#printconsolelevel[PrintConsoleLevel]
endif::[]

ifeval::["{adoc-build-target}" == "pdf"]
<<_printtestcolors>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_printtestcolors>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:print-ansi.html#printtestcolors[PrintTestColors]
endif::[]
|===

'''

[frame=none, grid=none, cols="a,a,a,a"]
|===

|
ifeval::["{adoc-build-target}" == "pdf"]
<<_testdirectoryexists>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_testdirectoryexists>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:system.html#testdirectoryexists[TestDirectoryExists]
endif::[]
|
ifeval::["{adoc-build-target}" == "pdf"]
<<_testdirectorywritable>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_testdirectorywritable>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:system.html#testdirectorywritable[TestDirectoryWritable]
endif::[]
|
ifeval::["{adoc-build-target}" == "pdf"]
<<_testfileexists>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_testfileexists>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:system.html#testfileexists[TestFileExists]
endif::[]

|
ifeval::["{adoc-build-target}" == "pdf"]
<<_testfilewritable>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_testfilewritable>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:system.html#testfilewritable[TestFileWritable]
endif::[]
|===

'''

[frame=none, grid=none, cols="a,a,a,a"]
|===

|
ifeval::["{adoc-build-target}" == "pdf"]
<<_writeruntimeconfig>>
endif::[]
ifeval::["{adoc-build-target}" == "html"]
<<_writeruntimeconfig>>
endif::[]
ifeval::["{adoc-build-target}" == "site"]
link:config.html#writeruntimeconfig[WriteRuntimeConfig]
endif::[]
| | |



|===

=== By Element

[frame=topbot, grid=rows, cols="d,d,d,d", options="header"]
|===

|===
