//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== Misc

Miscellaneous functions that do not fit into any other category.

=== ExitOnTaskErrors

_void ExitOnTaskErrors()_ - exits if any task errors are recorded.

The number of recorded task errors is taken from _$TASK_ERRORS_.
This variable will be altered by console functions such as
ifeval::["{adoc-build-target}" == "pdf"]
_<<_consoleerror>>_
endif::[]
ifeval::["{adoc-build-target}" == "html"]
_<<_consoleerror>>_
endif::[]
ifeval::["{adoc-build-target}" == "site"]
_link:console.html#consoleerror[ConsoleError]_
endif::[]
.
It can also be manipulated directly.
The exit uses the number of recorded task errors as exit code.

[source%nowrap,bash,linenumber]
----
ConsoleError "  ->" "unknown CLI option"
ExitOnTaskErrors
----

The example above throws an error in line 1 and the calls this function in line 2.
The result is that the current process will exit with the current number of task errors.

