//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== Tasks
Collection of functions for tasks.


=== GetTaskID

_String GetTaskID( $1 )_ - returns a task identifier (name) for a given short or long name.

*Parameters*:

* `$1` - String with the Id to process, which can be the task's short or long name.

*Return*:

* _String_ - the task name, empty if not found, i.e. no task is declared for the given identifier.
    The return is realized as a print of the found name or an empty string.

[source%nowrap,bash,linenumber]
----
TASK_ID=$(GetTaskID "my-name")
 if [[ -z ${TASK_ID:-} ]]; then
    # some error
else
    # some success
fi
----

The example above calls this function to return the task identifier for the string _my-name_ in line 1.
If the task was found, _TASK_ID_ will contain the name.
Otherwise, _TASK_ID_ will be empty.
The lines 2-6 test the return value.
In line 3 we can add some code for the error case.
In line 5 we can add some code for the success case.



=== BuildTaskHelpLine

_String BuildTaskHelpLine( $1, $2, $3, $4, [$5] )_ - builds a help line for a task's CLI option.

The help line is a single line for the task help screen.
The line is printed when all arguments have been validated and processed.
Otherwise error messages is printed.

The generated help line will use effects and colors.
Short and long option will be printed in _bold_ with an indentation of _3_.
If no short option is given, the long option will have a further indentation of _5_.
If short and long options are present, they will be separated by `⎵|⎵`.
The argument will be printed in _light-blue_.
The description will be printed as plain text.
See
ifeval::["{adoc-build-target}" == "pdf"]
_<<_printtesteffects>>_
endif::[]
ifeval::["{adoc-build-target}" == "html"]
_<<_printtesteffects>>_
endif::[]
ifeval::["{adoc-build-target}" == "site"]
_link:print-ansi.html#printtesteffects[PrintTestEffects]_
endif::[]
for how effects are printed in different _print modes_ and
ifeval::["{adoc-build-target}" == "pdf"]
_<<_printtestcolors>>_
endif::[]
ifeval::["{adoc-build-target}" == "html"]
_<<_printtestcolors>>_
endif::[]
ifeval::["{adoc-build-target}" == "site"]
_link:print-ansi.html#printtestcolors[PrintTestColors]_
endif::[]
for how colors are printed in different _print modes_.

*Parameters*:

* `$1` - String with the CLI short options, use _<none>_ for no short options.
* `$2` - String with the CLI long option, must not be empty
* `$3` - String with an argument, use _<none>_ for no argument.
    If an argument is given the string will be converted to all upper case letters.
* `$4` - String with the description of the option.
    This string should be a short tag line, not a full text description.
    It should fit on a single line.
* `$5`, optional -  Integer with the length (number of characters) to be used for short/long/argument.
    If empty or not provided, the default value _24_ is used.
    This value is the padding between short/long/argument and the description.

*Return*:

* _String_ - the final help line or an error message.
    The return is realized as a print.

*Errors* (as _Console Error_)

* If not short option was given in `$1`
* If not long option was given in `$2`
* If not argument was given in `$3`
* If not description was given in `$4`
* If _CONFIG_MAP["PRINT_MODE"]_ was set to an unknown value.
    This case can have multiple cause.
    It might be that the value was set bypassing the framework to a none-supported value.
    It might also be that a new _print mode_ was added to the framework, but this function was not updated.

[source%nowrap,bash,linenumber]
----
BuildTaskHelpLine h help "<none>" "print help screen and exit" 25
BuildTaskHelpLine f file file "file to open in viewer" 30
----

The example above shows two calls to this function.
Line 1 calls it with a short option _h_, a long option _help_, no argument, the description _print help screen and exit_, and length 25.
Line 2 calls it with a short option _f_, a long option _file_, an argument _FILE_, the description _file to open in viewer_, and a lenght of 30.
In this case, the argument will be changed to _FILE_.
The generated help lines for _print mode_ _ansi_ are shown below.

[source%nowrap,bash,linenumber,subs="attributes,quotes"]
----
   *-h* | *--help*              print help screen and exit
   *-f* | *--file* <span style="color: #0000FF">FILE</span>              file to open in viewer
----

All task in the framework are using this function to build help lines.
The task _clean_ for instance sets a variable for the length of _19_

[source%nowrap,bash,linenumber,indent=0,subs="attributes"]
----
include::{skb-site-main-dir}/main/bash/bin/tasks/mode-build/clean.sh[tags=helpline-padding]
----

and then uses the following code to build its three command line options:

[source%nowrap,bash,linenumber,indent=0,subs="attributes"]
----
include::{skb-site-main-dir}/main/bash/bin/tasks/mode-build/clean.sh[tags=helpline]
----

with the resulting output lines

[source%nowrap,bash,linenumber,subs="attributes,quotes"]
----
   *-f* | *--force*       force mode, not questions asked
   *-h* | *--help*        print help screen and exit
   *-s* | *--simulate*    print only, removes nothing, overwrites force
----



=== TaskGetCachedHelp

_String TaskGetCachedHelp( $1 )_ - returns a file name with cached help for a task.

This function tries to find a file with a help screen for the given task identifier, and returns it.
File is searched in the directory given by _CONFIG_MAP["CACHE_DIR"]_, with sub-directory _tasks_.
The file extension is taken from _CONFIG_MAP["PRINT_MODE"]_.
If the configuration is set to _/var/cache/skb-framework_,
    the task identifier is _clean_, and 
    the _print mode_ is set to _ansi_;
    the function will try to locate the file _/var/cache/skb-framework/tasks/clean.ansi_.

*Parameters*:

* `$1` - Task identifier (or name), must be the long name!

*Return*:

* _String_ - The file in the cache with a help screen for the task.
    The return is realized as a print of the found file name or an empty string if none was found.

*Errors* (as _Console Error_)

* If the task given by `$1` was not found

[source%nowrap,bash,linenumber]
----
CACHED_HELP=$(TaskGetCachedHelp "my-task")
----

The example above sets a variable _CACHED_HELP_ with the result of this function for a task with the name _my-task_.

All tasks in the framework use this function to locate a help screen in the cache, before they attempt to print help information.
The standard code used in the tasks is shown below (taken from the task _clean_):

[source%nowrap,bash,linenumber]
CACHED_HELP=$(TaskGetCachedHelp "clean")
if [[ -z ${CACHED_HELP:-} ]]; then
    # print help
else
    cat $CACHED_HELP
fi
----

Line 1 calls this function to locate a cached help file.
If the file was not found (test in line 2), the help is printed locally (line 3, actually a few print lines, usually some calls to
ifeval::["{adoc-build-target}" == "pdf"]
_<<_buildtaskhelpline>>_
endif::[]
ifeval::["{adoc-build-target}" == "html"]
_<<_buildtaskhelpline>>_
endif::[]
ifeval::["{adoc-build-target}" == "site"]
_link:tasks.html#buildtaskhelpline[BuildTaskHelpLine]_
endif::[]
).
Otherwise (line 4), the found file is printed (line 5).

