#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# ============LICENSE_START=======================================================
#  Copyright (C) 2018 Sven van der Meer. All rights reserved.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# SPDX-License-Identifier: Apache-2.0
# ============LICENSE_END=========================================================
#-------------------------------------------------------------------------------

##
## Module Core - the core module with essential elements
##
## @author     Sven van der Meer <vdmeer.sven@mykolab.com>
## @version    0.0.6
## @since      0.0.6
##


if [[ ! -n "${FW_MODULE_PATH:-}" ]]; then printf "  skb-framework: module \e[97mcore\e[0m \e[1m\e[91merror\e[0m when \e[3m\e[4mloading\e[0m: \$FW_MODULE_PATH not defined\n\n"; return; fi

Add element module Core CR ${FW_MODULE_PATH} "essential elements for the framework"

Add element application browser             with firefox         1 "--new-tab ##ARG1##" "web browser application with URL argument"
Add element application xterm               with xfce4-terminal  2 "--disable-server --title='##ARG1##' -x ##ARG2##" "XTerm application with title and command arguments"
Add element application pdfviewer           with evince          1 "##ARG1##" "PDF viewer application with file argument"


Add element dependency asciidoctor          with asciidoctor     "Asciidoctor processor"
Add element dependency asciidoctor-pdf      with asciidoctor-pdf "Asciidoctor processor, PDF backend"

Add element dependency tree                 with tree "list contents of directories in a tree-like format"

Add element dependency curl                 with curl "remote data transfer tool"
Add element dependency wget                 with wget "non-interactive download tool"

Add element dependency cloc                 with cloc "used to count Lines Of Code, static code analysis"

Add element dependency jdk                  with javac "JAVA Development Kit (JDK) 8"
Add element dependency jre                  with java  "JAVA Runtime Environment (JRE) 8"

Add element dependency gradle               with gradle "software build environment"
Add element dependency maven                with mvn    "software build environment"
    Dependency maven requires dependency jdk

Add element dependency ant                  with ant    "software build environment"
    Dependency ant requires dependency jdk

Add element dependency pgrep                with pgrep "lookup proccesses by name"
Add element dependency pkill                with pkill "kill proccesses by name"

Add element dependency biber                with biber    "bibliography processor in LaTeX"
Add element dependency bibtex               with bibtex   "bibliography processor in LaTeX"
Add element dependency lualatex             with lualatex "LaTeX processor"
Add element dependency pdflatex             with pdflatex "LaTeX processor"

Add element dependency python3              with python3 "Python language version 3"
Add element dependency pyyaml               with "${SF_HOME}/bin/tools/python-module.sh yaml" "YAML processor module for Python3"
    Dependency pyyaml requires dependency python3


Add element dir target                      with ---cd /tmp/target "target directory for software build tools"


Add element task describe-framework         with all ${FW_MODULE_PATH}/tasks/framework NO "describes aspects the framework"
Add element task describe-elements          with all ${FW_MODULE_PATH}/tasks/framework NO "general description of application elements"
Add element task describe-objects           with all ${FW_MODULE_PATH}/tasks/framework NO "general description of application objects"

Add element task list-configuration         with all ${FW_MODULE_PATH}/tasks/objects NO "lists the framework's configuration"
Add element task list-settings              with all ${FW_MODULE_PATH}/tasks/objects NO "lists the framework's settings"
Add element task list-formats               with all ${FW_MODULE_PATH}/tasks/objects NO "lists the framework's (print/log) formats"
Add element task list-levels                with all ${FW_MODULE_PATH}/tasks/objects NO "lists the framework's (print/log) levels"
Add element task list-modes                 with all ${FW_MODULE_PATH}/tasks/objects NO "lists the framework's (application) modes"


Add element task list-applications          with all ${FW_MODULE_PATH}/tasks/elements-list NO "lists applications"
Add element task list-dependencies          with all ${FW_MODULE_PATH}/tasks/elements-list NO "lists dependencies"
Add element task list-dirs                  with all ${FW_MODULE_PATH}/tasks/elements-list NO "lists directories (dirs)"
Add element task list-dirlists              with all ${FW_MODULE_PATH}/tasks/elements-list NO "lists directory lists"
Add element task list-files                 with all ${FW_MODULE_PATH}/tasks/elements-list NO "lists files"
Add element task list-filelists             with all ${FW_MODULE_PATH}/tasks/elements-list NO "lists file lists"
Add element task list-modules               with all ${FW_MODULE_PATH}/tasks/elements-list NO "lists modules"
Add element task list-options               with all ${FW_MODULE_PATH}/tasks/elements-list NO "lists (CLI) options"
Add element task list-projects              with all ${FW_MODULE_PATH}/tasks/elements-list NO "lists projects"
Add element task list-scenarios             with all ${FW_MODULE_PATH}/tasks/elements-list NO "lists scenarios"
Add element task list-tasks                 with all ${FW_MODULE_PATH}/tasks/elements-list NO "lists tasks"

Add element task describe-applications      with all ${FW_MODULE_PATH}/tasks/elements-describe NO "describes one or more applications"
Add element task describe-dependencies      with all ${FW_MODULE_PATH}/tasks/elements-describe NO "describes one or more dependencies"
Add element task describe-dirs              with all ${FW_MODULE_PATH}/tasks/elements-describe NO "describes one or more directories (dirs)"
Add element task describe-dirlists          with all ${FW_MODULE_PATH}/tasks/elements-describe NO "describes one or more directory lists"
Add element task describe-files             with all ${FW_MODULE_PATH}/tasks/elements-describe NO "describes one or more files"
Add element task describe-filelists         with all ${FW_MODULE_PATH}/tasks/elements-describe NO "describes one or more file lists"
Add element task describe-options           with all ${FW_MODULE_PATH}/tasks/elements-describe NO "describes one or more (CLI) options"
Add element task describe-projects          with all ${FW_MODULE_PATH}/tasks/elements-describe NO "describes one or more projects"
Add element task describe-scenarios         with all ${FW_MODULE_PATH}/tasks/elements-describe NO "describes one or more scenarios"
Add element task describe-tasks             with all ${FW_MODULE_PATH}/tasks/elements-describe NO "describes one or more tasks"

Add element task debug-tasks                with all ${FW_MODULE_PATH}/tasks/elements-debug NO "prints debug information for one or more tasks"

Add element task sf-validate                with dev ${FW_MODULE_PATH}/tasks/installation YES "validates the framework"
