## maps to flaten naming edge cases and static component properties
## {name,,} means the name, plural, lower case
## components with special plural spelling (e.g. dependency/dependencies) can get 2 entries in each map

declare -A -g FW_COMPONENTS_SINGULAR                ## [name,,]="all lower case singular of the term for elements, instances, objects"
declare -A -g FW_COMPONENTS_PLURAL                  ## [name,,]="all lower case plural of the term for elements, instances, objects"
declare -A -g FW_COMPONENTS_TITLE_LONG_SINGULAR     ## [name,,]="Long Title, singular"
declare -A -g FW_COMPONENTS_TITLE_LONG_PLURAL       ## [name,,]="Long Title, plural"
declare -A -g FW_COMPONENTS_TITLE_SHORT_SINGULAR    ## [name,,]="Short Title, singular"
declare -A -g FW_COMPONENTS_TITLE_SHORT_PLURAL      ## [name,,]="Short Title, plural"
declare -A -g FW_COMPONENTS_TABLE_DESCR             ## [name,,]="text for table head when showing taglines"
declare -A -g FW_COMPONENTS_TABLE_VALUE             ## [name,,]="text for table head when showing values"
declare -A -g FW_COMPONENTS_TABLE_DEFVAL            ## [name,,]="text for table head when showing default values"
declare -A -g FW_COMPONENTS_TABLE_EXTRA             ## [name,,]="Extra properties in table", empty if none
declare -A -g FW_COMPONENTS_TAGLINE                 ## [name,,]="tagline", i.e. s short description

## create entries for the 4 components, they don't have a function defined
FW_COMPONENTS_SINGULAR["actions"]="action"
    FW_COMPONENTS_PLURAL["actions"]="actions"
    FW_COMPONENTS_TITLE_LONG_SINGULAR["actions"]="Action"
    FW_COMPONENTS_TITLE_LONG_PLURAL["actions"]="Actions"
    FW_COMPONENTS_TITLE_SHORT_SINGULAR["actions"]="Action"
    FW_COMPONENTS_TITLE_SHORT_PLURAL["actions"]="Actions"
    FW_COMPONENTS_TABLE_DESCR["actions"]="Description"
    FW_COMPONENTS_TABLE_VALUE["actions"]="Description"
    FW_COMPONENTS_TABLE_EXTRA["actions"]=""
FW_COMPONENTS_SINGULAR["elements"]="element"
    FW_COMPONENTS_PLURAL["elements"]="elements"
    FW_COMPONENTS_TITLE_LONG_SINGULAR["elements"]="Element"
    FW_COMPONENTS_TITLE_LONG_PLURAL["elements"]="Elements"
    FW_COMPONENTS_TITLE_SHORT_SINGULAR["elements"]="Element"
    FW_COMPONENTS_TITLE_SHORT_PLURAL["elements"]="Elements"
    FW_COMPONENTS_TABLE_DESCR["elements"]="Description"
    FW_COMPONENTS_TABLE_VALUE["elements"]="Description"
    FW_COMPONENTS_TABLE_EXTRA["elements"]=""
FW_COMPONENTS_SINGULAR["instances"]="instance"
    FW_COMPONENTS_PLURAL["instances"]="instances"
    FW_COMPONENTS_TITLE_LONG_SINGULAR["instances"]="Instance"
    FW_COMPONENTS_TITLE_LONG_PLURAL["instances"]="Instances"
    FW_COMPONENTS_TITLE_SHORT_SINGULAR["instances"]="Instance"
    FW_COMPONENTS_TITLE_SHORT_PLURAL["instances"]="Instances"
    FW_COMPONENTS_TABLE_DESCR["instances"]="Description"
    FW_COMPONENTS_TABLE_VALUE["instances"]="Description"
    FW_COMPONENTS_TABLE_EXTRA["instances"]=""
FW_COMPONENTS_SINGULAR["objects"]="object"
    FW_COMPONENTS_PLURAL["objects"]="objects"
    FW_COMPONENTS_TITLE_LONG_SINGULAR["objects"]="Object"
    FW_COMPONENTS_TITLE_LONG_PLURAL["objects"]="Objects"
    FW_COMPONENTS_TITLE_SHORT_SINGULAR["objects"]="Object"
    FW_COMPONENTS_TITLE_SHORT_PLURAL["objects"]="Objects"
    FW_COMPONENTS_TABLE_DESCR["objects"]="Description"
    FW_COMPONENTS_TABLE_VALUE["objects"]="Description"
    FW_COMPONENTS_TABLE_EXTRA["objects"]=""

