declare -A FW_INSTANCE_EXC_LONG     ## [long]="description"

FW_RUNTIME_MAPS_LOAD+=" FW_INSTANCE_EXC_LONG"

FW_INSTANCE_EXC_LONG["00"]="normal exit"
FW_INSTANCE_EXC_LONG["01"]="general error during initialization, load, or option processing" ## e.g. unknown print format set in CLI
FW_INSTANCE_EXC_LONG["02"]="command 'realpath' not found"
FW_INSTANCE_EXC_LONG["03"]="\$SF_HOME does not exist or is not a directory"
FW_INSTANCE_EXC_LONG["04"]="\$SF_HOME not set"
FW_INSTANCE_EXC_LONG["05"]="wrong bash major version, requires minimum 4"
FW_INSTANCE_EXC_LONG["06"]="wrong bash minor version, requires minimum 2"
FW_INSTANCE_EXC_LONG["07"]="did not find GNU (Extended) getopt"
FW_INSTANCE_EXC_LONG["08"]="missing core dependency core-utils"
FW_INSTANCE_EXC_LONG["09"]="missing important dependency"
FW_INSTANCE_EXC_LONG["10"]="framework not loaded"
FW_INSTANCE_EXC_LONG["11"]="error while reading the set configuration file"
FW_INSTANCE_EXC_LONG["12"]="error while reading the default configuration file"
FW_INSTANCE_EXC_LONG["13"]="error loading settings from the environment"
FW_INSTANCE_EXC_LONG["14"]="error(s) executing task"
FW_INSTANCE_EXC_LONG["15"]="error(s) executing scenario"
FW_INSTANCE_EXC_LONG["16"]="requested command for execution not found"
FW_INSTANCE_EXC_LONG["17"]="error(s) executing command"
