//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


==  ConsoleHas()
_boolean ConsoleHas( $1 )_ - returns true if requested counter is larger than 0, false otherwise.

This function tests the counter requested in `$1` and returns
    _true_ if the counter is larger than _0_ and
    _false_ in any other case.
For requests to _errors_ and _warnings_, the function will use the setting of _CONFIG_MAP["RUNNING_IN"]_ to determine which actual counter has to be used.
The setting here is done automatically by the framework.
One of the following three settings is possible:

* _loader_ - the current code runs in the loader, the counter for errors or warnings in the loader will be used,
* _shell_ - the current code runs in the shell, the counter for errors or warnings in the shell will be used, or
* _task_ - the current code runs in a task, the counter for errors or warnings in tasks will be used,


*Parameter*

* `$1` - String with the requested counter.
            The string can be
            _errors_ or
            _warnings_.


*Return*

* _true_ (or _0_) if the counter is larger than _0_
* _false_ (or _1_) if the counter is not larger than _0_


*Errors*

* For an unknown counter in `$1`


*Internal Dependencies*

* {blank}
include::{skb-site-main-dir}/doc/fragments/developer-guide/api/function-links/consoleprint-link.adoc[]
for printing error messages.


*Examples*

[source%nowrap,bash,linenumber]
----
if $(ConsoleHas errors); then ...; ...; fi
if $(ConsoleHas errors); then ...; else ...; fi
if $(ConsoleHas errors); then
    ...
    return
fi

if $(ConsoleHas warnings); then ...; ...; fi
if $(ConsoleHas warnings); then ...; else ...; fi
if $(ConsoleHas warnings); then
    ...
    return
fi
----

The examples above show how this function can be used to test error and warning counters.
Line 1 and 2 show single line evaluations for errors.
The lines 3-6 show a multi-line example for the error counter.
Line 8 and 9 show single line evaluations for warnings.
The lines 11-13 show a multi-line example for the warning counter.
