//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== DescribeDependency()
_void DescribeDependency( $1, $2, $3, [$4])_ - describes a dependency with various options.

This function describes the dependency _$1_ using the print option _$2_, the print feature(s) _$3_, and an optional print mode _$4_.


*Parameter*

* `$1`, _string_ - the dependency identifier to process, long- or short form
* `$2`, _string_ - the print option, one of:
    ** _standard_ - prints one line for the dependency: name and tag line.
    ** _full* - prints _standard_ plus the dependency description.
* `$3`, _string_ - the print features.
    One or more of the features can be used.
    If no special feature should be used, use `none`.
    Separate multiple features using a blank ` `.
    The following features are supported:
    ** `none` - does activate no feature.
        Can be used when no feature should be used but a specific print mode (_$4_) is required.
        Note: has no effect if used with other features.
    ** `line-indent` - prints an indentation of 6 blanks before the line, except when in print mode _adoc_.
    ** `enter`  - prints a new line at the end of the description.
    ** `post-line` - prints a double colon after the line as `::`.
    ** `adoc` - prints a description in _adoc_ taken from the dependency declaration.
    ** `ansi` -  prints a description with plain text formatting taken from dependency declaration.
    ** `text` - actually any string starting with `text` - prints a description with plain text formatting taken from dependency declaration.
* `$4`, _string_, optional - the requested print mode.
    If present, the requested print mode will be used.
    If not present, the default (currently set) print mode will be used.
    Note: this parameter is independent of _$3_!


*Errors*

* For an unknown dependency identifier (name)
* For unknown print features
* For an unknown print option


*Internal Dependencies*

* {blank}
include::{skb-site-main-dir}/doc/fragments/developer-guide/api/function-links/consoleprint-link.adoc[]
to print errors.
* {blank}
include::{skb-site-main-dir}/doc/fragments/developer-guide/api/function-links/printeffect-link.adoc[]
to print the effects.


*External Dependencies*

* `cat` - to print the description text, if requested


*Examples*

[source%nowrap,bash,linenumber]
----
DescribeDependency asciidoctor full "ansi line-indent" ansi
----

The example above calls the function to get a full description of the dependency _asciidoctor_,
    with the line indentation,
    description using ANSI formatting, and
    the forced print mode _ansi_.

[source%nowrap,subs="attributes,quotes"]
----
      *asciidoctor* - Asciidoctor processor
        Asciidoctor is a tool (or rather tool chain) that takes files  written
        in AsciiDoc (or ADOC)  and  produces  various  output  formats.  These
        formats are supported by backends. Standard backends are PDF and  HTM.
        Others are supported by plugins. For details on  Asciidoctor  and  its
        installation see https://asciidoctor.org/ .
----

The screen above shows the result of the function call.
