//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//

== GetTaskID

_String GetTaskID( $1 )_ - returns a task identifier (name) for a given short or long name.

*Parameters*:

* `$1` - String with the Id to process, which can be the task's short or long name.

*Return*:

* _String_ - the task name, empty if not found, i.e. no task is declared for the given identifier.
    The return is realized as a print of the found name or an empty string.

[source%nowrap,bash,linenumber]
----
TASK_ID=$(GetTaskID "my-name")
 if [[ -z ${TASK_ID:-} ]]; then
    # some error
else
    # some success
fi
----

The example above calls this function to return the task identifier for the string _my-name_ in line 1.
If the task was found, _TASK_ID_ will contain the name.
Otherwise, _TASK_ID_ will be empty.
The lines 2-6 test the return value.
In line 3 we can add some code for the error case.
In line 5 we can add some code for the success case.


