//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//

== ListFunctions()
_void ListFunctions( [$1] )_ - lists all defined API functions.

Prints all defined API functions.
If used without an argument, the functions will be printed in one line.
If _$1_ is set to anything, each function will be printed in a separate line.


*Parameters*:

* `$1`, _mixed_ - if used (set to anything), each function will be printed in a separate line.


*External Dependencies*

* `cut` - to print only functions.


*Examples*

[source%nowrap,bash,linenums]
----
ListFunctions
ListFunctions true
----

The examples above call the function to print all API functions in s a single line (line 1) or in separate lines (line 2).

[source,indent=0,subs="attributes"]
----
include::{skb-site-target-dir}/adoc-text/api-function-list.txt[]
----

The output for line is shown in the screen above.
