//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== OptionElementDescription()
_void OptionElementDescription( $1, $2 )_ - prints general description for options.

This function prints text describing options in general, runtime options, and exit options; as requested in _$1_.
The text is formatting for the print mode _$2_.
The actual text is taken from

* _CONFIG_MAP["MANUAL_SRC"]}/elements/options_, with _$1_ as file extension for options
* _CONFIG_MAP["MANUAL_SRC"]}/elements/exit-options_, with _$1_ as file extension for options
* _CONFIG_MAP["MANUAL_SRC"]}/elements/run-options_, with _$1_ as file extension for options

This function is used by the task _describe-element_.


*Parameters*

* `$1`, _string_ - the type of option to describe:
** `option` for options in general,
** `runtime` for runtime options, or
** `exit` for exit options.
* `$2`, _string_ - the print mode for text formatting.


*Internal Dependencies*

* {blank}
include::{skb-site-main-dir}/doc/fragments/developer-guide/api/function-links/consoleprint-link.adoc[]
for throwing errors.


*External Dependencies*

* `cat` to print the contents of the documentation file.


*Examples*

[source%nowrap,bash,linenumber]
----
OptionElementDescription option ansi
OptionElementDescription exit ansi
OptionElementDescription runtime ansi
----

The example above will print the text with ANSI formatting.


