//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== ParameterTagline()
_void ParameterTagline( $1, $2, [$3] )_ - prints the parameter tagline with formatting (padding).

This function prints the parameter tag line (the one line or short description) with padding after the text.
The overall length is taken from _CONSOLE_MAP["PARAM_DESCRIPTION_LENGTH"]_.
The line is printed as follows:

** If the tag line for the parameter is smaller (less characters) than the overall length, then
    the description is taken as is.
    If _$3_ is set to any value, then extra padding will be appended to the line.
    Otherwise, no padding will be appended.
** Otherwise, the line is shortened to the overall length minus four characters and the final character of the line are printed as `...`.

An adjustment to the padding can be done setting _$2_ to a non-negative integer.
If used, the overall length will be reduced by the number given, including a requested padding at the end of the text.


*Parameter*

* `$1`, _string_ - the parameter identifier, any spelling (upper case, lower case, mixed).
* `$2`, _integer_ - an adjustment for indentation, _0_ if none required.
* `$3`, _mixed_ - any value to avoid trailing padding (_$2_ to a number, e.g. 0).


*Errors*

* For unknown parameter identifiers (names)


*Internal Dependencies*

* {blank}
include::{skb-site-main-dir}/doc/fragments/developer-guide/api/function-links/consoleprint-link.adoc[]
to print errors.
* {blank}
include::{skb-site-main-dir}/doc/fragments/developer-guide/api/function-links/getparameterid-link.adoc[]
to retrieve the parameter identifier.


*Examples*

[source%nowrap,bash,linenums]
----
ParameterTagline BROWSER 3 none
ParameterTagline BROWSER
----

The examples above call the function for the parameter _BROWSER_.
Line 1 requires an adjustment of three characters but no trailing padding.
Line 2 does not require an adjustment but a trailing padding.

[source%nowrap,subs="attributes,quotes"]
----
command for browser
command for browser⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵
----

The two lines above show the printed taglines for the examples.
