//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== PathToSystemPath()
_String PathToSystemPath( $1 )_ - converts a path to a system-specific representation.

This can be important when running on hybrid systems.
In _Cygwin_ for instance, one can execute Windows programs that do not understand UNIX paths.
Note: most conversions have an effect only when absolute paths are used.

The system is taken from `CONFIG_MAP["SYSTEM"]`.
If no special path conversion is implemented for the system, the original path is returned.
The return is realized as a print.
Supported conversions are:

* Cygwin using `cygpath -m` for the conversion


*Parameters*

* `$1` - the path to convert.


*Return*

* _String_ with the original or converted path.


*External Dependencies*

* On _Cygwin_: `cygpath`, which is part of a standard installation.


*Examples*

[source%nowrap,bash,linenums]
----
VARIABLE=$(PathToSystemPath /cygdrive/c/dev/framework/target/site/index.html)
----

On a cygwin system, the function will convert the path to a _mixed_ representation
`C:/dev/framework/target/site/index.html`.
On all other system, the original path will not be changed.
