//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//


== PromptSfMode

_void PromptSfMode()_ - prints the application flavor plus the mode in round brackets.

The application flavor is taken from _CONFIG_MAP["FLAVOR"]_.
It is printed as all lower case.
The application mode is printed using
ifeval::["{adoc-build-target}" == "pdf"]
_<<_printappmode>>_
endif::[]
ifeval::["{adoc-build-target}" == "html"]
_<<_printappmode>>_
endif::[]
ifeval::["{adoc-build-target}" == "site"]
_link:api/print.html#printappmode[PrintAppMode]_
endif::[]
.
A colon `:` is added after the application mode.
The prompt is printed as a line, with `\n`.

[source%nowrap,bash,linenumber]
----
PromptSfMode
----

The example above simply calls the function.
Assuming that the application flavor is _std_,
    that the application mode is _all_, and
    that _print mode_ is set to _ansi_,
    this call will result in the following printed line.

[source%nowrap,bash,linenumber,subs="attributes,quotes"]
----
std(<span style="color: #FF0000">all</span>):

----

