//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== ScenarioInTable()
_string ScenarioInTable( $1, [$2] )_ - returns main scenario details for table views.

This function prints the scenario long- and short name, and a padding in one line.
No newline will be printed.
Scenario names will be formatted using the requested print mode (_$2_) or the set print mode of the application.
The padding is calculated using the setting of _CONSOLE_MAP["SCN_PADDING"]_ and the length of the text line.
The return is realized as print.


*Parameters*

* `$1`, _string_ - the scenario identifier (name), long- or short form
* `$2`, _string_, optional - an optional print mode, standard setting used if not present.


*Return*

* _string_, the line with a leading space, scenario with long- and short name, and padding

*Errors*

* For unknown scenario identifier
* For unknown print mode


*Internal Dependencies*

* {blank}
include::{skb-site-main-dir}/doc/fragments/developer-guide/api/function-links/describescenario-link.adoc[]
to get the formatted scenario details.
* {blank}
include::{skb-site-main-dir}/doc/fragments/developer-guide/api/function-links/consoleprint-link.adoc[]
for throwing errors.


*Examples*

[source%nowrap,bash,linenums]
----
ScenarioInTable build-fw-cache
----

The example above calls he function for the scenario _build-fw-cache_.
Possible return values are shown below:

[source%nowrap,subs="attributes,quotes"]
----
⎵build-fw-cache, bfc⎵⎵⎵⎵⎵⎵⎵⎵
⎵*build-fw-cache*, *bfc*⎵⎵⎵⎵⎵⎵⎵⎵
----

The first line shows plain text, the second line ANSI formatted text.
