//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== TestFS()
_void TestFS( $1, $2, $3, [$4] )_ - tests an artifact in the file-system for some properties.

This function takes an artifact described in `$1` of type `$2` and tests properties as requested in `$3`.
The last, optional, argument is text used in error messages.
The artifacts can be files or directories, with leading path if required.


*Parameters*

* `$1` - _String_ - A file or directory, with leading paths (direct or indirect) if required.
* `$2` - _String_ - The type of the artifact.
        For a file use `f` or `file`.
        For a directory use `d`, `dir`, or `directory`.
* `$3` - _String_ - 
        One or more properties that have to be tested.
        Separate the properties with a comma.
        Supported properties are:
        ** `e` or `exists` for artifact does exist (and is of given type)
        ** `r` or `read` for artifact is readable
        ** `w` or `write` for artifact is writable
* `$4` - _String_, optional - add-on for error messages, used in place as the calling task or function.
        If not given, the function name itself will be used.


*Errors*

* If no argument `$1` was given, no test is performed in this case.
* If no argument `$2` was given, no test is performed in this case.
* If no argument `$3` was given, no test is performed in this case.
* If any of the requested property tests fail.


*Internal Dependencies*

* {blank}
include::{skb-site-main-dir}/doc/fragments/developer-guide/api/function-links/consoleprint-link.adoc[]
for throwing errors.


*Examples*

[source%nowrap,bash,linenumber]
----
TestFS "src/main/bash/doc/manual/skb-framework.html" file exists,read "site-fw"
----

The example above tests if the artifact
    _src/main/bash/doc/manual/skb-framework.html_
    if type _file_
    does _exist_ and is _readable_.
The callee _site-fw_ should be used for error messages.


The example above tests if a directory `./target/site` exists and is readable.
If the file does not exist, the following error message will be printed (and the error counter for _tasks_ will be increased by 1).

[source%nowrap,subs="attributes,quotes"]
----
  -> <span style="color: #FF0000">[Error]</span>: site-fw: file does not exist: src/main/bash/doc/manual/skb-framework.html
----



The following example the function, but does not provide the third argument `$3`.

[source%nowrap,bash,linenumber]
----
TestFS "src/main/bash/etc/manual" dir exists
----

In this case, the following error will be printed.

[source%nowrap,subs="attributes,quotes"]
----
  -> <span style="color: #FF0000">[Error]</span>: TestFS: no properties given
----
