//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== The Loader

The loader is the script `$FW_HOME/bin/loader/loader.sh`.
It is responsible for all initial configuration, loading elements, testing settings and dependencies, processing command line arguments (options), and execute task, scenarios, or the shell.
The load process has multiple steps, starting with some initial settings and finished with a cleanup.

The initial settings are shown in the source block below.
Line 1 restricts _bash_, providing a safer execution environment.
Line 2 allows for extended globbing (finding files recursively with wildecards such as `**/*.adoc`).
Line 3 takes the current time.
This information is later used to calculate how long the load process did take.
Line 4 removes an environment setting that prints rather annoying messages when running Java.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=init]
----


=== Dependencies

The first real action in the load process is the test for core dependencies.
The source block below shows how the loader tests for:

* _BASH_ version 4 - needed to use associative arrays (or maps)
* GNU _Getopt_ - extensively used in the loader and tasks to parse command lines
* _bc_ - a calculator used for calculating execution time of tasks and scenarios
* _mktemp_ - used to create names for temporary directories, required to store runtime configuration information

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=core-dep]
----


=== Core and default Settings

Once all dependencies are satisfied, the loader realizes core settings:

* If not set, then set `$FW_HOME` (lines 1-4)
* Source the loaders declaration files (line 6).
    This will create the main configuration map called `CONFIG_MAP` along with the map `CONFIG_SRC`.
* Set core variables in the configuration map (lines 7-25):
    ** _FW_HOME_ - the home directory of the framework
    ** _RUNNING_IN_ - set to loader, this will later be changed the `shell` or `task` by the shell and tasks
    ** _SYSTEM_ - to know in which system the framework is running
    ** _CONFIG_FILE_ - the SKB configuration file
    ** _STRICT_ - set strict mode to `off`, at least initially
    ** _APP_MODE_ - set the default application mode to `use`
    ** _APP_MODE_FLAVOR_ - set the default flavor of the application mode to `std` (standard)
    ** _PRINT_MODE_ - set the default print mode to `ansi` (for ANSI formatted text with colors and effects)
    ** Levels - set the levels for loader, shell, and tasks initially to `error`
    ** Quiet - set quiet mode for loader, shell, and tasks to `off`, i.e. they are _not_ quiet
    ** _SCENARIO_PATH_ - create an empty path for scenarios
    ** _SHELL_SNP_ - activate shell prompt

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=core-settings]
----



=== Core Includes
Next, some core files from the framework's API are loaded.
To makes things simple, the provided `_include` file is used to load all API functions.
Then, the loaders own function for parsing the command line is loaded.
This only loads the function, it does not actually parse the command line.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=core-includes]
----



=== Application Flavor and Name
The next step is to set the flavor and application name/script.
The flavor is any prefix used by the application to identify parameters.
It must be provided by the application (which starts the loader) as the setting `__FW_LOADER_FLAVOR`.
Once flavor and application settings are realized, the application map and version are loaded.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=flavor-app]
----



=== Temporary Directory
The next step is to test if the temporary directory can be created.
This is important for two reasons:

* The directory uses the application flavor in the same, to separate several SKB applications that might be running on the same host
* In the directory, the loader will safe to runtime configuration.
    This is required because associative arrays (or hash maps, or maps), used to store all configuration data, cannot be exported into the _bash_ environment.
    Using temporary files is the only way for the loader to share the configuration with the shell, and for the shell to share it with tasks.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=tmp-dir]
----



=== Sneak Preview of CLI Arguments
Next, the loader does a sneak preview inside the command line arguments.
This is done to determine the application mode that might be requested from the command line.
We need to know the requested mode here, before we actually do parse the arguments later.
This is important to load the correct declarations for all elements.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=sneak-cli]
----



=== Parameter Declarations
With the application mode set, the loader can load the parameter declarations.
These declarations can only be loaded from source, i.e. not from an optional cache, since one of the parameters actually sets the cache directory.
Once loaded (line 1), all loaded parameters are processed (line 4).
This function will load values from the environment, then from an optional configuration file, and finally from potentially declared default values.
This function only loads settings, it does not test any of these settings.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=param-decl]
----



=== Option Declarations
Next is the declaration of command line options.
This declaration can be done from cache (if cached) or source (if no cache exists).
Errors here indicate bugs or runtime problems.
Once declared, all options are set to `false` in the CLI map (lines 8-11).
This allows to test which options have been used as actual arguments when parsing the command line later.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=opt-decl]
----



=== Parse Command Line Arguments
Now the loader can safely parse the command line arguments.
The parse function does parse for most options, only set options that have no further side effect.
This means that this function does not execute on any option.
This is done later in the load process.
The print mode is immediately set and tested (lines 3-12) to make sure we have a valid setting for it.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=parse-cli]
----



=== Realize early Exit Options
At this stage, the loader can realize early exit options.
Those are options that do not require any further actions by the loader.
These options include:

* Clean the cache (lines 1-5),
* Print the help screen (lines 6-9), and
* Print the application version (lines 10-13)

If any of these options was requested, the loader will exit with code _0_, success.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=exit-options]
----



=== Declarations for Commands and Error Codes
Now the declarations of shell commands (lines 1-7) and error codes (lines 8-14) can be loaded, either from cache or source.
Errors here indicate a framework bug or runtime problem, since commands and error codes are core features and rather static.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=cmdec-decl]
----



=== Dependency Declarations
The next step is to load dependency declarations, either from cache or from source.
Errors here can point to a bug in the framework, a problem in the application, or a problem with a dependency declaration itself.
In this step, dependencies are only declared, but not tested, since the loader still does not know which of them are required by tasks.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=dep-decl]
----



=== Task Declarations
This step is probably the most complicated and most important step in the load process.
First, the declarations of tasks are loaded, either from cache or from source (lines 1-8).
Errors here can point to a bug in the framework, a problem in the application, or a problem with a task declaration itself.
Next, the loaded tasks are processed (line 9-11).
This function will take the loaded tasks and test or validate all parameters and dependencies they require.
This process can take some time, especially for testing external dependencies.
Errors tend to indicate configuration or dependency problems, not internal or declaration problems.

Some tasks might declare requirements as _optional_.
Those dependencies only throw warnings in a normal application run.
Only if an application is run in _strict_ mode will those problems throw errors.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=task-decl]
----



=== Scenario Declarations
When tasks are declared, the loader can declare all scenarios from the framework and application home as well as the optional scenario path.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=scn-decl]
----



=== Set Levels
The next step is to set the correct levels (log levels) for the loader (the remaining load steps), the shell, and the tasks.
This is done for each level type in separation.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=set-levels]
----



=== Do (Exit) Options
At this stage, the loader can process most the remaining exit options.
Those are command line options that request some behavior and then should cause the loader to exit.

If such options are requested, the loader might provide some information about its execution time (lines 5-11).

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=do-options]
----



=== Create Runtime Configuration File
Now, the loader needs to create the temporary runtime configuration file.
The remaining actions are either to run a execute a task, run a scenario, or execute the interactive shell.
All of these actions require the configuration to be available.
The configuration file is created in the already tested directory, usually located in `/tmp/`.
The name of the configuration files includes a time stamp of its creation and an arbitrary, random string.
`mktemp` is used to create the file name.
Since the name is unique, the same application can be executed many times simultaneously.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=tmp-file]
----



=== Execute Task or Scenario
The final exit options are to execute a task or to run a scenario.
The loader will try either of them.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=tsk-scn]
----



=== Start Shell
This is the final step of the load process.
If no task or scenario was requested to be executed, the loader will start the interactive shell.
This shell will run until a user caused it or exit, or until an error terminated the whole application.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=shell]
----



=== Clean Up
Finally, the loader can cleanup and prepare to terminate.
Cleanup basically means to remove the temporary configuration file.
If the temporary directory is no longer needed, i.e. no other configuration exists in it, it can be removed as well.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=cleanup]
----



=== Done
The loader is done, all actions have been taken.
It now can safely exit and return the execution to the `skb-framework` or the calling application.
A final message is displayed to mark this point in the process.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/loader/loader.sh[tags=done]
----

