//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (vdmeer.sven@mykolab.com)
//


== skb-framework

The `skb-framework` is the main entry point to the framework.
It realizes two things in one.
First, it is an application itself.
Second, it is a start script that can be used by other applications to start the framework.

At the start, it checks the setting `__FW_LOADER_FLAVOR` (line 1 in the source block below).
If this variable is set, then another application wants to start the framework.
Otherwise, the `skb-framework` is the application.
In the later case, the script sets required variables for the loader (lines 3-5 below):

* `__FW_LOADER_FLAVOR` - the flavor of the application, here `SF`
* `__FW_LOADER_SCRIPTNAME` - the name of the script (application)
* `__FW_LOADER_APPNAME` - the application name

The next step is to find the framework installation.
The script tries the variable `SF_HOME` first, `readlink` first (lines 8-13), if that fails `dirname` (lines 15-19).
If all attempts fail, the script terminates with an error (lines 20-24).
Otherwise it set `FW_HOME`. 

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/skb-framework[tags=self-flavor]
----


If `skb-framework` is used by another application to start the framework, the script only tries to find the framework installation.
The mechanism here is the same as explained above: try `FW_HOME` first, then `readlink`, then `dirname`.
IF all fails, exit with an error.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/skb-framework[tags=app-flavor]
----


One the framework installation has been found, the script tests if the loader exists.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/skb-framework[tags=check-loader]
----

When all conditions are satisfied, the script executes the loader handing over all arguments unprocessed.

[source%nowrap,bash,linenums,subs="attributes+"]
----
include::{skb-site-main-dir}/main/bash/bin/skb-framework[tags=start-loader]
----
