== List of shell commands

*bye* - exit shell:: 
Exits the shell and the program. 
If the program was not started in forced mode (see CLI option `--force`), the temporary configuration file will be removed. 
The exit status is `0`.

*cls*, *clear-screen* - clear screen:: 
Clear screen.


*c*, *configuration* - shows current configuration:: 
Prints the current time as HH:mm:ss. 
This can come in handy when no other clock or watch is available. 
It is a separate command because the prompt should not be overloaded.

*es*, *execute-scenario* SCENARIO - executes a scenario:: 
Clear screen.


*exit* - exit shell:: 
Exits the shell and the program. 
If the program was not started in forced mode (see CLI option `--force`), the temporary configuration file will be removed. 
The exit status is `0`.

*h*, *help* - show help screen:: 
Shows a help screen with all shell commands. 
The commands are grouped as: _history_, _exit_, _help_, _tasks_, _scenarios_, and _misc_. 
The help screen uses colors for arguments: green for optional arguments and red for mandatory arguments. 
Note: for commands with multiple arguments, the sequence is important!

*!*, *history* NUMBER - show history or run history command:: 
Shows the history of shell commands. 
Each command, once executed, is automatically added to the history, if the previous command was not exactly the same. 
The history accepts an optional parameter _NUMBER_. 
When a number (an integer) is given, the command with that number in the history will be executed. 
If the number does not exist in the history, an error is printed.

*ls*, *list-scenarios* - list scenarios:: 
Clear screen.


*q*, *quit* - quit shell:: 
Exits the shell and the program. 
If the program was not started in forced mode (see CLI option `--force`), the temporary configuration file will be removed. 
The exit status is `0`.

*t*, *tasks* - prints list of available (loaded) tasks:: 
Prints the current time as HH:mm:ss. 
This can come in handy when no other clock or watch is available. 
It is a separate command because the prompt should not be overloaded.

*T*, *time* - prints the current time as HH:mm:ss:: 
Prints the current time as HH:mm:ss. 
This can come in handy when no other clock or watch is available. 
It is a separate command because the prompt should not be overloaded.


