== List of parameters
*BROWSER* - command for browser:: 
Sets the command and URL substitution to start a web browser with a given URL.  
The URL substitution string has the form `%URL%`. 
To start for instance Firefox, this variable should be set to `firefox --new-tab %URL%`.
+
default value: none defined

*CACHE_DIR* - directory for caching settings:: 
Prompt
+
default value: `/var/cache/skb-framework`

*MANUAL_SRC* - source folder for the manual:: 
A tool...
+
default value: `$FW_HOME/etc/manual`

*MVN_SITES* - Maven sites:: 
Sets the directory for the SKB sites. 
These sites are build using the Maven site plugin. 
If not present, the tasks that build sites will not execute.
+
default value: none defined

*PDF_READER* - command for pdf reader:: 
Name of a PDF reader.
+
default value: none defined

*SHELL_PROMPT* - sets the shell prompt:: 
Prompt
+
default value: `sf: `

*SKB_FW_TOOL* - SKB Tool:: 
This option points to the SKB Framework Tool. 
This tool is an executable JAR. 
It is used to convert paragraphs and lists into justified text with pre-defined margins and other parameters. 
This is done using the SKB _asciiparagraph_ and _asciilist_ implementations. 
This setting is required to build the manual sources (text files) from the original ADOC files.
In a standard installation, the JAR will be available in the `bin/java` folder of the framework.
+
default value: `$FW_HOME/bin/java/skb-framework-tool-0.0.0-all.jar`

*SKB_LIBRARY* - SKB library:: 
Sets the directory for the SKB library. 
This directory can contain actual publication artifacts, such as PDF files or sources and any other material. 
The folder structure for the library is not fixed.
+
default value: none defined

*TARGET* - target folder:: 
Sets the directory in which the program should build policies and policy artifacts. 
This directory will be created if it does not exist. 
On clean, the whole directory will be removed!
+
default value: none defined

*XTERM* - command for xterm:: 
Sets the command to start a new X terminal (Xterm) with substitution strings for title and command. 
The title substitution string is `%TITLE%`. 
The command substitution string is `%COMMAND%`. 
For most X terminals, it is best to use an open ended CLI option for the program, i.e. a CLI option that takes everything until the end of the command line. 
Most X terminal variants can be started using `xterm -T %TITLE% -e %COMMAND%`. 
For `mintty` on Cygwin this variable should be `mintty -t %TITLE% %COMMAND%`. 
For an XFCE4 terminal, e.g. on Ubuntu, this variable should be `xfce4-terminal --disable-server --title='%TITLE%' -x %COMMAND%`.
+
default value: none defined

