//
// ============LICENSE_START=======================================================
// Copyright (C) 2018-2019 Sven van der Meer. All rights reserved.
// ================================================================================
// This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International Public License
// Full license text at https://creativecommons.org/licenses/by-sa/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-SA-4.0
// ============LICENSE_END=========================================================
//
// @author     Sven van der Meer (vdmeer.sven@mykolab.com)
// @version    0.0.5
//


== Requirements

The framework is written in `bash`.
It uses associative arrays, also known as hash maps.
Thus version 4 or higher of `bash` is required.

There are a few other requirements to start the framework.
They are listed in the table below.
All of the here listed requirements are tested during the application load, i.e. before the interactive shell is started.

Note: these requirements are for the framework (start script, loader, interactive shell, and API).
Tasks can define any other dependency to external applications and tools.
Those dependencies are tested at runtime (start and load).

[cols="10,80", grid=rows, frame=none, %autowidth.stretch, options="header"]
|===
| Dependency | Description

| `bash` |
The Bash shell version 4 or higher.
On most UNIX/Linux system, Bash 4 will be part of a standard installation.

| `bc` |
This is an arbitrary precision calculator (language and application).
It is used here to calculate the execution time of tasks and scenarios (since Bash does not offer floating point arithmetic).
`bc` should be standard in almost all UNIX systems.

See also the link:https://www.gnu.org/software/bc/manual/html_mono/bc.html[GNU manual page].

| `cat` |
This standard tool concatenates files and prints them to the standard output.
The loader is using `cat` to read the version files.

| (GNU) `getopt` |
The framework requires command line parsing for its own CLI arguments as well for every task.
It uses the GNU enhanced version of `getopt`.
The standard version is not supported.

| `less` |
As the manual states: "less is the opposite of more".
It essentially allows to show a file and move backwards and forwards, search the content, and more interactions.
The `manual` option and command is using `less` to show the manual.


| (GNU) `mktemp` |
The framework needs to create a temporary directory with runtime configuration files.
It uses `mktemp` to create temporary file and directory names.
This tool should be standard in Linux distributions.

See also the link:https://www.gnu.org/software/autogen/mktemp.html[GNU page].

| `sed` |
The UNIX stream editor, used to manipulate text or files.
The application is required by some API functions.

| `tput` |
This tool can be used to initialize a terminal or to query the terminal database (_terminfo_).
The `manual` option and command is using `tput` to store (`smcup`) and restore (`rmcup`) the terminal context when showing the manual.

|===


//cut, date

