#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# ============LICENSE_START=======================================================
#  Copyright (C) 2018 Sven van der Meer. All rights reserved.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# SPDX-License-Identifier: Apache-2.0
# ============LICENSE_END=========================================================
#-------------------------------------------------------------------------------

##
## Module Core - the core module with essential elements
##
## @author     Sven van der Meer <vdmeer.sven@mykolab.com>
## @version    0.0.6
## @since      0.0.6
##


if [[ ! -n "${FW_MODULE_PATH:-}" ]]; then printf "  skb-framework: module \e[97mcore\e[0m \e[1m\e[91merror\e[0m when \e[3m\e[4mloading\e[0m: \$FW_MODULE_PATH not defined\n\n"; return; fi

Add element module Coretest CT ${FW_MODULE_PATH} "essential elements for the framework"

if [[ -r  "${FW_OBJECT_CFG_VAL["CACHE_DIR"]}/modules/Coretest.cache" ]]; then
    source "${FW_OBJECT_CFG_VAL["CACHE_DIR"]}/modules/Coretest.cache"
else
    FW_CURRENT_MODULE_NAME=Coretest
        Add requirement for module Coretest as module Core

        Add element scenario test-simple to module with all ${FW_MODULE_PATH}/scenarios/test YES "simple scenario for testing API functions"

        Add element scenario test-task-help to module with all ${FW_MODULE_PATH}/scenarios/test YES "runs all tasks with '--help'"
            Add required task debug-tasks to            scenario test-task-help
            Add required task describe-applications to  scenario test-task-help
            Add required task describe-dependencies to  scenario test-task-help
            Add required task describe-dirs to          scenario test-task-help
            Add required task describe-elements to      scenario test-task-help
            Add required task describe-files to         scenario test-task-help
            Add required task describe-framework to     scenario test-task-help
            Add required task describe-objects to       scenario test-task-help
            Add required task describe-options to       scenario test-task-help
            Add required task describe-projects to      scenario test-task-help
            Add required task describe-scenarios to     scenario test-task-help
            Add required task describe-tasks to         scenario test-task-help
            Add required task list-applications to      scenario test-task-help
            Add required task list-configuration to     scenario test-task-help
            Add required task list-dependencies to      scenario test-task-help
            Add required task list-dirs to              scenario test-task-help
            Add required task list-dirlists to          scenario test-task-help
            Add required task list-files to             scenario test-task-help
            Add required task list-filelists to         scenario test-task-help
            Add required task list-formats to           scenario test-task-help
            Add required task list-levels to            scenario test-task-help
            Add required task list-modes to             scenario test-task-help
            Add required task list-modules to           scenario test-task-help
            Add required task list-options to           scenario test-task-help
            Add required task list-projects to          scenario test-task-help
            Add required task list-scenarios to         scenario test-task-help
            Add required task list-settings to          scenario test-task-help
            Add required task list-tasks to             scenario test-task-help

        Add element scenario test-list-tasks to module with all ${FW_MODULE_PATH}/scenarios/test YES "runs list tasks with various options"
            Add required task list-applications to      scenario test-list-tasks
            Add required task list-configuration to     scenario test-list-tasks
            Add required task list-dependencies to      scenario test-list-tasks
            Add required task list-dirs to              scenario test-list-tasks
            Add required task list-dirlists to          scenario test-list-tasks
            Add required task list-files to             scenario test-list-tasks
            Add required task list-filelists to         scenario test-list-tasks
            Add required task list-formats to           scenario test-list-tasks
            Add required task list-levels to            scenario test-list-tasks
            Add required task list-modes to             scenario test-list-tasks
            Add required task list-modules to           scenario test-list-tasks
            Add required task list-options to           scenario test-list-tasks
            Add required task list-projects to          scenario test-list-tasks
            Add required task list-scenarios to         scenario test-list-tasks
            Add required task list-settings to          scenario test-list-tasks
            Add required task list-tasks to             scenario test-list-tasks

        Add element scenario test-describe-tasks to module with all ${FW_MODULE_PATH}/scenarios/test YES "runs describe tasks with various options"
            Add required task describe-applications to  scenario test-describe-tasks
            Add required task describe-dependencies to  scenario test-describe-tasks
            Add required task describe-dirs to          scenario test-describe-tasks
            Add required task describe-dirlists to      scenario test-describe-tasks
            Add required task describe-elements to      scenario test-describe-tasks
            Add required task describe-files to         scenario test-describe-tasks
            Add required task describe-filelists to     scenario test-describe-tasks
            Add required task describe-framework to     scenario test-describe-tasks
            Add required task describe-objects to       scenario test-describe-tasks
            Add required task describe-options to       scenario test-describe-tasks
            Add required task describe-projects to      scenario test-describe-tasks
            Add required task describe-scenarios to     scenario test-describe-tasks
            Add required task describe-tasks to         scenario test-describe-tasks

        Add element scenario test-debug-tasks to module with all ${FW_MODULE_PATH}/scenarios/test YES "runs debug tasks with various options"
            Add required task debug-tasks to            scenario test-describe-tasks

        Add element scenario test-exec-app to module with all ${FW_MODULE_PATH}/scenarios/test YES "tests execute application in a scenario"
            Add required application browser to         scenario test-exec-app

    unset FW_CURRENT_MODULE_NAME
fi
