#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# ============LICENSE_START=======================================================
#  Copyright (C) 2018 Sven van der Meer. All rights reserved.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# SPDX-License-Identifier: Apache-2.0
# ============LICENSE_END=========================================================
#-------------------------------------------------------------------------------

##
## Module Core - the core module with essential elements
##
## @author     Sven van der Meer <vdmeer.sven@mykolab.com>
## @version    0.0.6
## @since      0.0.6
##


if [[ ! -n "${FW_MODULE_PATH:-}" ]]; then printf "  skb-framework: module \e[97mcore\e[0m \e[1m\e[91merror\e[0m when \e[3m\e[4mloading\e[0m: \$FW_MODULE_PATH not defined\n\n"; return; fi

Add element module Coretest CT ${FW_MODULE_PATH} "essential elements for the framework"
    Module Coretest requires module Core


Add element scenario test-simple with test ${FW_MODULE_PATH}/scenarios/test YES "simple scenario for testing API functions"
    Scenario test-simple requires task list-configuration
    Scenario test-simple requires task debug-tasks

Add element scenario test-task-help with test ${FW_MODULE_PATH}/scenarios/test YES "runs all tasks with '--help'"
    Scenario test-task-help requires task debug-tasks
    Scenario test-task-help requires task describe-applications
    Scenario test-task-help requires task describe-dependencies
    Scenario test-task-help requires task describe-dirs
    Scenario test-task-help requires task describe-elements
    Scenario test-task-help requires task describe-files
    Scenario test-task-help requires task describe-framework
    Scenario test-task-help requires task describe-objects
    Scenario test-task-help requires task describe-options
    Scenario test-task-help requires task describe-projects
    Scenario test-task-help requires task describe-scenarios
    Scenario test-task-help requires task describe-tasks
    Scenario test-task-help requires task list-applications
    Scenario test-task-help requires task list-configuration
    Scenario test-task-help requires task list-dependencies
    Scenario test-task-help requires task list-dirs
    Scenario test-task-help requires task list-dirlists
    Scenario test-task-help requires task list-files
    Scenario test-task-help requires task list-filelists
    Scenario test-task-help requires task list-formats
    Scenario test-task-help requires task list-levels
    Scenario test-task-help requires task list-modes
    Scenario test-task-help requires task list-modules
    Scenario test-task-help requires task list-options
    Scenario test-task-help requires task list-projects
    Scenario test-task-help requires task list-scenarios
    Scenario test-task-help requires task list-settings
    Scenario test-task-help requires task list-tasks

Add element scenario test-list-tasks with test ${FW_MODULE_PATH}/scenarios/test YES "runs list tasks with various options"
    Scenario test-list-tasks requires task list-applications
    Scenario test-list-tasks requires task list-configuration
    Scenario test-list-tasks requires task list-dependencies
    Scenario test-list-tasks requires task list-dirs
    Scenario test-list-tasks requires task list-dirlists
    Scenario test-list-tasks requires task list-files
    Scenario test-list-tasks requires task list-filelists
    Scenario test-list-tasks requires task list-formats
    Scenario test-list-tasks requires task list-levels
    Scenario test-list-tasks requires task list-modes
    Scenario test-list-tasks requires task list-modules
    Scenario test-list-tasks requires task list-options
    Scenario test-list-tasks requires task list-projects
    Scenario test-list-tasks requires task list-scenarios
    Scenario test-list-tasks requires task list-settings
    Scenario test-list-tasks requires task list-tasks

Add element scenario test-describe-tasks with test ${FW_MODULE_PATH}/scenarios/test YES "runs describe tasks with various options"
    Scenario test-describe-tasks requires task describe-applications
    Scenario test-describe-tasks requires task describe-dependencies
    Scenario test-describe-tasks requires task describe-dirs
    Scenario test-describe-tasks requires task describe-dirlists
    Scenario test-describe-tasks requires task describe-elements
    Scenario test-describe-tasks requires task describe-files
    Scenario test-describe-tasks requires task describe-filelists
    Scenario test-describe-tasks requires task describe-framework
    Scenario test-describe-tasks requires task describe-objects
    Scenario test-describe-tasks requires task describe-options
    Scenario test-describe-tasks requires task describe-projects
    Scenario test-describe-tasks requires task describe-scenarios
    Scenario test-describe-tasks requires task describe-tasks

Add element scenario test-debug-tasks with test ${FW_MODULE_PATH}/scenarios/test YES "runs debug tasks with various options"
    Scenario test-describe-tasks requires task debug-tasks

Add element scenario test-exec-app with test ${FW_MODULE_PATH}/scenarios/test YES "tests execute application in a scenario"
    Scenario test-exec-app requires application browser

